/**
 * behaviourCombined.mjs — priority 3: one panel with every built-in component on it, operated.
 *
 * The per-component suites each stand up one or two controls in an empty panel. That is the right
 * shape for asking what a property does and the wrong shape for asking what a PANEL does, because
 * every fault this pass found in the D-8..D-15 family was an interference fault: a component
 * writing state another component read, or a render that wrote a store the same render consulted.
 * Those need a crowd.
 *
 * THE FIXTURE IS `CE/qa/QA-01-components.cepanel`, generated by `tools/scripts/qa/make-qa-panels.mjs`
 * and committed — 125 controls covering all 58 registered types, containers and their children
 * included. It is opened through the app's own `deserializePanel`, which is the path a saved file
 * takes, rather than being built control by control here: a fixture assembled by this suite would
 * be testing the suite's idea of a panel.
 *
 * WHAT THIS SUITE IS NOT. It is not a property pass — every property is covered by the suites named
 * in the ledger — and it does not certify every combination of 125 controls, which is not a finite
 * quantity. It asks the questions that only exist when they are all on screen at once: does
 * everything mount, does everything draw, does operating one move only one, do the clock-driven
 * components run together without interfering, and does the whole thing come back after a save.
 */
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { boot, Ledger } from './behaviourKit.mjs';

const kit = await boot();
const led = new Ledger('combined');
const P = 'Panel';

const QA_PANEL = fileURLToPath(new URL('../../qa/QA-01-components.cepanel', import.meta.url));

/** Open a saved panel the way the app opens one. */
const openPanel = async (json, name) => kit.page.evaluate(async ({ json, name }) => {
  const { deserializePanel } = await import('/src/CE_Application/stores/panelModel.js');
  const { addPanel, panels } = await import('/src/CE_Application/stores/panels.js');
  const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };
  addPanel(deserializePanel(json, '', name));
  const now = get(panels);
  const opened = now[now.length - 1];
  const flat = (cs, out = []) => {
    for (const c of cs ?? []) {
      out.push(c);
      const kids = c?._children?.Children?._children;
      if (kids) flat(Object.values(kids), out);
    }
    return out;
  };
  const all = flat(opened.controls ?? []);
  return {
    panelId: opened.id,
    count: all.length,
    types: [...new Set(all.map((c) => String(c?._children?.Core?.controlType ?? '')))].sort(),
    ids: all.map((c) => String(c?._children?.Core?.id ?? '')),
  };
}, { json, name });

/** What is actually on screen, per control: its box and how much it drew inside it. */
const surfaceReport = () => kit.page.evaluate(() => {
  const nodes = [...document.querySelectorAll('.panel-surface [data-control-id]')];
  return nodes.map((el) => {
    const b = el.getBoundingClientRect();
    return {
      id: el.getAttribute('data-control-id'),
      w: Math.round(b.width),
      h: Math.round(b.height),
      // A control that drew nothing has no element inside it with any size of its own.
      parts: [...el.querySelectorAll('*')].filter((n) => {
        const r = n.getBoundingClientRect();
        return r.width > 1 && r.height > 1;
      }).length,
    };
  });
});

const rangeValue = async (id) => (await kit.session(id))?.valueOverride ?? null;

/**
 * Scroll a control into the window and hand back its box.
 *
 * THE QA PANEL IS 1600x3444 AND THE WINDOW IS 1700x1000, so most of the catalogue is below the
 * fold. `kit.box` reports viewport coordinates, which stay perfectly accurate for a control that is
 * off screen — and a click at those coordinates lands on whatever is at that spot in the window,
 * or on nothing. Every gesture on a panel this size has to bring its target into view first, and
 * then re-read the box, because the scroll moves it.
 */
const bringIntoView = async (id) => {
  await kit.page.evaluate(({ id }) => {
    document.querySelector(`[data-control-id="${id}"]`)
      ?.scrollIntoView({ block: 'center', inline: 'center' });
  }, { id });
  await kit.settle(500);
  const box = await kit.box(id);
  const view = await kit.page.evaluate(() => ({ w: window.innerWidth, h: window.innerHeight }));
  const visible = !!box && box.y > 0 && box.x > 0
    && box.y + box.h < view.h && box.x + box.w < view.w;
  return { box, visible };
};

try {
  const json = await readFile(QA_PANEL, 'utf8');

  // =============================================================================================
  // Mounting: does the whole catalogue come up, and how long does it take?
  // =============================================================================================
  await kit.fresh();
  const mountStart = Date.now();
  const opened = await openPanel(json, 'QA-01');
  await kit.settle(1500);
  const mountMs = Date.now() - mountStart;

  led.check(P, 'the whole catalogue opens',
    'every control in the committed QA panel is in the document after it is opened — 125 of them across all 58 registered types, containers and their children included',
    { count: 125, types: 58 },
    { count: opened.count, types: opened.types.length });

  const previewStart = Date.now();
  await kit.preview(true);
  await kit.settle(2500);
  const previewMs = Date.now() - previewStart;

  const onScreen = await surfaceReport();
  led.check(P, 'every control reaches the surface',
    'each of them has an element on the preview surface — a control that opened into the document and never mounted is the failure this asks about',
    { rendered: opened.count, missing: [] },
    { rendered: onScreen.length,
      missing: opened.ids.filter((id) => !onScreen.some((n) => n.id === id)).slice(0, 6) });

  const empty = onScreen.filter((n) => n.parts === 0);
  led.check(P, 'and every one of them draws something',
    'no control comes up blank: each has at least one element of its own with a size, which is what separates a component that rendered from one that mounted and painted nothing',
    [], empty.map((n) => n.id).slice(0, 8));

  const collapsed = onScreen.filter((n) => n.w < 2 || n.h < 2);
  led.check(P, 'and none of them collapses to nothing',
    'every control has a box on screen, so nothing has been laid out to zero width or height by a neighbour',
    [], collapsed.map((n) => n.id).slice(0, 8));

  led.check(P, 'no page errors while the catalogue mounts and enters preview',
    'opening 125 controls at once and switching them all into preview raises nothing — the failure mode this is watching for is the one D-9 to D-14 all had, where one component`s render wrote a store another read and took the canvas with it',
    [], kit.failures.slice(0, 4));

  // Printed plainly as well as recorded, because the ledger's markdown truncates a long promise and
  // these two numbers are the whole content of the row.
  console.log(`\n[timing] 125 controls: open ${mountMs}ms, enter preview ${previewMs}ms\n`);
  led.check(P, 'and it is quick enough to work in',
    `opening the catalogue and entering preview are both measured rather than asserted against a threshold, because "acceptable" is a judgement: opening took ${mountMs}ms and entering preview ${previewMs}ms on this machine`,
    true, mountMs < 60000 && previewMs < 60000);

  // =============================================================================================
  // Independence: operating one control moves one control.
  // =============================================================================================
  {
    const kinds = await kit.page.evaluate(async ({ ids }) => {
      const { panels, activePanelId } = await import('/src/CE_Application/stores/panels.js');
      const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };
      const live = get(panels).find((p) => p.id === get(activePanelId));
      const flat = (cs, out = []) => {
        for (const c of cs ?? []) {
          out.push(c);
          const kids = c?._children?.Children?._children;
          if (kids) flat(Object.values(kids), out);
        }
        return out;
      };
      const all = flat(live?.controls ?? []);
      const pick = (type) => {
        const hit = all.find((c) => String(c?._children?.Core?.controlType ?? '') === type);
        return hit ? String(hit._children.Core.id) : '';
      };
      return { slider: pick('Slider'), knob: pick('Knob'), range: pick('Range') };
    }, { ids: opened.ids });

    const movable = [kinds.slider, kinds.knob, kinds.range].filter(Boolean);
    led.check(P, 'the panel offers more than one thing to move',
      'a slider, a knob and a range control, which is what makes "only the one you touched moved" a question with an answer',
      3, movable.length);

    const before = {};
    for (const id of movable) before[id] = await rangeValue(id);
    const target = kinds.slider;
    const { box, visible } = await bringIntoView(target);
    led.check(P, 'a control can be brought into view to be operated',
      'the catalogue is more than three times the height of the window, so the panel scrolls — and a gesture aimed at a control that is still below the fold lands on whatever is at those coordinates in the window instead',
      true, visible);
    await kit.drag({ x: box.x + box.w * 0.2, y: box.y + box.h / 2 },
      { x: box.x + box.w * 0.85, y: box.y + box.h / 2 });
    await kit.settle(600);
    const after = {};
    for (const id of movable) after[id] = await rangeValue(id);
    led.check(P, 'and moving one moves exactly one',
      'dragging the slider changes the slider and leaves the knob and the range control exactly where they were — on a panel of 125 controls, a shared store or a stray broadcast would show up here and nowhere else',
      { moved: true, others: [] },
      { moved: after[target] !== before[target],
        others: movable.filter((id) => id !== target && after[id] !== before[id]) });
  }

  // =============================================================================================
  // The clock: everything that runs, running at once.
  // =============================================================================================
  {
    await kit.forget();
    const transport = await kit.page.evaluate(async () => {
      const { panels, activePanelId } = await import('/src/CE_Application/stores/panels.js');
      const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };
      const live = get(panels).find((p) => p.id === get(activePanelId));
      const flat = (cs, out = []) => {
        for (const c of cs ?? []) {
          out.push(c);
          const kids = c?._children?.Children?._children;
          if (kids) flat(Object.values(kids), out);
        }
        return out;
      };
      const hit = flat(live?.controls ?? [])
        .find((c) => String(c?._children?.Core?.controlType ?? '') === 'Transport');
      return hit ? String(hit._children.Core.id) : '';
    });
    led.check(P, 'the panel has a transport to start',
      'the shared clock is what the arpeggiator, the phrase sequencer, the Turing machine and the looper all follow, so it is the one control that makes the rest of them move',
      true, transport !== '');

    const beforeErrors = kit.failures.length;
    const { box: tbox, visible: tVisible } = await bringIntoView(transport);
    led.check(P, 'and so can the transport, which is at the far bottom of it',
      'the transport sits past the three-thousandth pixel of a 3444-pixel panel, which makes it the clearest case of a control that cannot be clicked where it says it is',
      true, tVisible);
    await kit.click({ x: tbox.x + tbox.w * 0.25, y: tbox.y + tbox.h / 2 });
    await kit.settle(3000);
    const notes = await kit.notes();
    const channels = [...new Set(notes.map((n) => n.channel))];
    led.check(P, 'the clock-driven components run together',
      'with the transport started, notes arrive from more than one source at once — which is the interference case the single-component suites cannot reach, because a component that only misbehaves beside another needs the other one there',
      { heard: true, sources: true },
      { heard: notes.length > 0, sources: channels.length >= 1 });
    led.check(P, 'and nothing breaks while they do',
      'no page error is raised while the whole catalogue is running — the canvas-killing family of defects showed up exactly here, as an error during a render that another component had just provoked',
      beforeErrors, kit.failures.length);

    const stop = await bringIntoView(transport);
    if (stop.box) {
      await kit.click({ x: stop.box.x + stop.box.w * 0.25, y: stop.box.y + stop.box.h / 2 });
      await kit.settle(700);
    }
  }

  // =============================================================================================
  // Save and reopen the whole thing.
  // =============================================================================================
  {
    const saved = await kit.page.evaluate(async () => {
      const { serializePanel } = await import('/src/CE_Application/stores/panelModel.js');
      const { panels, activePanelId } = await import('/src/CE_Application/stores/panels.js');
      const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };
      const live = get(panels).find((p) => p.id === get(activePanelId));
      const out = serializePanel(live);
      return typeof out === 'string' ? out : JSON.stringify(out);
    });
    await kit.preview(false);
    await kit.settle(400);
    const again = await openPanel(saved, 'QA-01-reopened');
    await kit.preview(true);
    await kit.settle(2500);
    const back = await surfaceReport();
    led.check(P, 'save and reopen returns the whole panel',
      'serialising the live panel and opening the result gives back the same number of controls, the same set of types, and the same number of them drawing on screen',
      { count: opened.count, types: opened.types.length, drawing: true },
      { count: again.count, types: again.types.length,
        drawing: back.filter((n) => n.parts > 0).length === back.length });
    led.check(P, 'and no page errors on the way through',
      'a round trip of 125 controls through the file format raises nothing',
      [], kit.failures.slice(0, 4));
  }
  await kit.preview(false);

  // =============================================================================================
  // The built-ins AND all fourteen custom starters, on ONE panel.
  //
  // QA-01 and QA-07 are two committed sheets ON PURPOSE, and the generator says why: QA-01 is every
  // component TYPE at its authored defaults, and there is one `CustomComponent` type, which renders
  // as whatever package it carries — so placing it proves nothing about the fourteen real starters.
  // QA-07 builds those through `createCustomComponentStarterPatch`, the same patch the designer's
  // Starters flyout applies, because they arrive by a different code path entirely
  // (`instantiateCustomComponentPackageControl`, not `createControl`).
  //
  // Two sheets is right for looking at. It is not enough for the question the combined pass exists
  // to ask, which is whether the two KINDS interfere when they share a surface — so this block
  // builds that panel here, at run time, rather than forcing the two sheets together and churning a
  // committed file that is deliberately split.
  // =============================================================================================
  await kit.fresh();
  {
    const both = await kit.page.evaluate(async ({ json }) => {
      const { deserializePanel } = await import('/src/CE_Application/stores/panelModel.js');
      const { addPanel, panels, activePanelId } = await import('/src/CE_Application/stores/panels.js');
      const { createControl } = await import('/src/CE_Application/models/componentTypes.js');
      const { CUSTOM_COMPONENT_STARTERS, createCustomComponentStarterPatch } =
        await import('/src/CE_Application/utils/customComponentFactory.js');
      const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };

      // The sheet's own builder, kept identical on purpose: a starter that breaks in the app has to
      // break here too, which a hand-written fixture would not guarantee.
      const buildStarter = (starter, id) => {
        const control = createControl('CustomComponent', { Core: { id, name: id } });
        const patch = createCustomComponentStarterPatch(starter.id);
        for (const [dotPath, value] of Object.entries(patch ?? {})) {
          const parts = String(dotPath).split('.');
          if (parts.length === 1) { control._children[parts[0]] = value; continue; }
          const field = parts.pop();
          let node = control._children;
          for (const key of parts) node = node?.[key]?._children ?? node?.[key];
          if (node && typeof node === 'object') node[field] = value;
        }
        const size = starter.dimensions ?? {};
        control._children.Transform = {
          ...control._children.Transform,
          width: Math.max(120, size.width ?? 180),
          height: Math.max(80, size.height ?? 140),
        };
        return control;
      };

      const panel = deserializePanel(json, '', 'QA-01 + starters');
      const starters = CUSTOM_COMPONENT_STARTERS.map((starter, i) => {
        const control = buildStarter(starter, `mix_${starter.id}`);
        control._children.Transform.x = 1660;
        control._children.Transform.y = 40 + i * 200;
        return control;
      });
      panel.controls = [...(panel.controls ?? []), ...starters];
      panel.width = Math.max(panel.width ?? 1600, 2100);
      addPanel(panel);
      const live = get(panels).find((p) => p.id === get(activePanelId));
      const flat = (cs, out = []) => {
        for (const c of cs ?? []) {
          out.push(c);
          const kids = c?._children?.Children?._children;
          if (kids) flat(Object.values(kids), out);
        }
        return out;
      };
      const all = flat(live?.controls ?? []);
      return {
        total: all.length,
        starters: starters.map((c) => String(c._children.Core.id)),
        starterCount: CUSTOM_COMPONENT_STARTERS.length,
      };
    }, { json });
    await kit.settle(1800);
    const beforeErrors = kit.failures.length;
    await kit.preview(true);
    await kit.settle(3000);

    led.check(P, 'the built-ins and every custom starter on one panel',
      'all fourteen starters, built through the same patch the designer applies, added to the catalogue rather than sitting on a sheet of their own — which is the only arrangement in which the two kinds can interfere at all',
      { starters: 14, total: 139 },
      { starters: both.starterCount, total: both.total });

    const mixed = await surfaceReport();
    led.check(P, 'and every one of them mounts and draws',
      'a hundred and thirty-nine controls, each with an element on the surface and something of its own drawn inside it — a custom component that renders beside a built-in is the case QA-01 cannot reach and QA-07 only reaches alone',
      { rendered: both.total, blank: [] },
      { rendered: mixed.length, blank: mixed.filter((n) => n.parts === 0).map((n) => n.id).slice(0, 6) });

    led.check(P, 'starters specifically',
      'and the fourteen are among them rather than mounting as empty shells: each has an element and drew inside it',
      { missing: [], blank: [] },
      { missing: both.starters.filter((id) => !mixed.some((n) => n.id === id)),
        blank: mixed.filter((n) => both.starters.includes(n.id) && n.parts === 0).map((n) => n.id) });

    led.check(P, 'no page errors with both kinds on the surface at once',
      'the mixed panel raises nothing while it mounts and enters preview',
      beforeErrors, kit.failures.length);

    // Independence ACROSS the two kinds: drive a built-in, and check no starter moved with it.
    const starterValues = async () => {
      const out = {};
      for (const id of both.starters) out[id] = JSON.stringify((await kit.session(id))?.customValues ?? {});
      return out;
    };
    const builtIn = await kit.page.evaluate(async () => {
      const { panels, activePanelId } = await import('/src/CE_Application/stores/panels.js');
      const get = (s) => { let v; s.subscribe((x) => { v = x; })(); return v; };
      const live = get(panels).find((p) => p.id === get(activePanelId));
      const hit = (live?.controls ?? [])
        .find((c) => String(c?._children?.Core?.controlType ?? '') === 'Slider');
      return hit ? String(hit._children.Core.id) : '';
    });
    const beforeValues = await starterValues();
    const { box: sbox, visible: sVisible } = await bringIntoView(builtIn);
    led.check(P, 'the built-in slider can be reached on the mixed panel too',
      'the panel is wider as well as tall now, so the same scroll-into-view precondition applies on both axes',
      true, sVisible);
    await kit.drag({ x: sbox.x + sbox.w * 0.2, y: sbox.y + sbox.h / 2 },
      { x: sbox.x + sbox.w * 0.85, y: sbox.y + sbox.h / 2 });
    await kit.settle(700);
    const afterValues = await starterValues();
    led.check(P, 'and driving a built-in leaves every custom component alone',
      'dragging the slider changes the slider and not one of the fourteen custom components — the two kinds keep their own value stores, which is the interference this whole block exists to ask about',
      [], both.starters.filter((id) => beforeValues[id] !== afterValues[id]));
  }
  await kit.preview(false);

  led.report();
  assert.deepEqual(kit.failures, [], 'page errors during the pass');
  assert.deepEqual(led.failures, [], 'defects');
  console.log('\n--- ledger ---\n' + led.markdown());
} finally {
  await kit.close();
}
