import { flatControls } from '../../../CE/web/src/CE_Application/utils/containment.js';
import { createScript } from '../../../CE/web/src/CE_Application/scripting/scriptModel.js';

// What you hear, at a glance. A tone that is switched off dims its whole row; an effect whose TYPE is
// OFF dims and locks its four parameter knobs, which do nothing until a type is chosen.
//
// Nothing dims until the value is KNOWN: received from the GAIA (a read or an echo, which raises
// onParameterReceived even when the value matches the default) or changed here. Every one of these
// defaults to OFF in the profile, so dimming from the defaults would open an unconnected panel with
// the whole instrument greyed out, which says less than it seems to.
//
// A tone row is dimmed, not locked: you can still set a tone up before switching it on. The script
// fades the row's section containers, so frames, captions and controls dim together, and it only
// writes when something changes.
export const DIMMED = 0.35;

export function activeStateScript(config) {
  return `// Dim switched-off tones and lock effect knobs while TYPE is OFF.
// Generated by tools/scripts/gaia-panel/active-state.mjs. Controls are addressed by ID.

var CONFIG = ${JSON.stringify(config, null, 2)};

function isOn(v) { return v === true || v === 1 || v === "1" || String(v).toLowerCase() === "on"; }
function isOff(v) { return v === false || v === 0 || v === "0" || String(v).toLowerCase() === "off"; }

function opacity(id, value) {
  var current = get(id + ".opacity");
  if ((current == null ? 1 : Number(current)) !== value) set(id + ".opacity", value);
}
function enabled(id, value) {
  var current = get(id + ".enabled");
  if ((current == null ? true : current !== false) !== value) set(id + ".enabled", value);
}

function showTone(tone, on) {
  for (var i = 0; i < tone.members.length; i++) opacity(tone.members[i], on ? 1 : CONFIG.dimmed);
}
function showEffect(effect, off) {
  for (var i = 0; i < effect.knobs.length; i++) {
    enabled(effect.knobs[i], !off);
    opacity(effect.knobs[i], off ? CONFIG.dimmed : 1);
  }
  for (var j = 0; j < effect.captions.length; j++) opacity(effect.captions[j], off ? CONFIG.dimmed : 1);
}

function onPanelLoad() {
  // Unknown until told: undo anything a saved panel carried over, then wait for a real value.
  CONFIG.tones.forEach(function (tone) {
    showTone(tone, true);
    watch(tone.switchId + ".value", function () { showTone(tone, isOn(get(tone.switchId))); });
  });
  CONFIG.effects.forEach(function (effect) {
    showEffect(effect, false);
    watch(effect.typeId + ".value", function () { showEffect(effect, isOff(get(effect.typeId))); });
  });
  on("*", "onParameterReceived", function (info) {
    if (!info || (info.role && info.role !== CONFIG.role)) return;
    CONFIG.tones.forEach(function (tone) { if (info.parameter === tone.parameter) showTone(tone, isOn(info.value)); });
    CONFIG.effects.forEach(function (effect) { if (info.parameter === effect.parameter) showEffect(effect, isOff(info.value)); });
  });
}
`;
}

/**
 * Runs on the SECTIONED panel, after names lose their dots: a tone row is the section containers
 * in its `toneN` group (LFO, OSC, FILTER, AMP, MOD LFO), so dimming a row is five writes and takes
 * the section frames, captions and controls with it. The group's TONE SELECT / ON / COPY controls
 * are not sections and are never dimmed — TONE n ON is how you bring the row back.
 */
export function applyActiveState(panel, role) {
  const all = flatControls(panel.controls);
  const named = (name) => all.find(c => c._children.Core.name === name);
  const need = (name) => {
    const c = named(name);
    if (!c) throw new Error(`active-state: missing ${name}`);
    return c;
  };
  const id = (name) => need(name)._children.Core.id;
  const parameterOf = (control) => control._children.DeviceBindings?.bindings?.find(b => b.parameterId)?.parameterId;
  const tones = [1, 2, 3].map(tone => {
    const group = need(`tone${tone}`);
    const members = Object.values(group._children.Children?._children ?? {})
      .filter(c => c._children.Core.controlType === 'Container')
      .map(c => c._children.Core.id);
    if (members.length === 0) throw new Error(`active-state: tone${tone} has no sections`);
    const toneSwitch = need(`common_tone${tone}Switch`);
    return { parameter: parameterOf(toneSwitch) ?? `common.tone${tone}Switch`, switchId: toneSwitch._children.Core.id, members };
  });
  const effects = ['distortion', 'flanger', 'delay', 'reverb'].map(effect => {
    const type = need(`${effect}_type`);
    return {
      parameter: parameterOf(type) ?? `${effect}.type`,
      typeId: type._children.Core.id,
      knobs: [1, 2, 3, 4].map(i => id(`${effect}_parameter${i}`)),
      captions: [1, 2, 3, 4].map(i => id(`${effect}_parameter${i}_caption`)),
    };
  });
  const script = createScript({
    id: 'gaia_active_state', name: 'Dim what is switched off', language: 'javascript',
    scope: 'panel', event: 'onPanelLoad', target: '*',
    description: 'Dims a switched-off tone row and locks effect knobs while TYPE is OFF, once the value is known. Sends no MIDI.',
    source: activeStateScript({ role, dimmed: DIMMED, tones, effects }),
  });
  const existing = (panel.scripts ?? []).findIndex(s => s.id === script.id);
  if (existing < 0) panel.scripts = [...(panel.scripts ?? []), script];
  else panel.scripts[existing] = script;
  return panel;
}
