import { flatControls } from '../../../CE/web/src/CE_Application/utils/containment.js';
import { createScript } from '../../../CE/web/src/CE_Application/scripting/scriptModel.js';

// What you hear, at a glance. A tone that is switched off dims its whole row; an effect whose TYPE is
// OFF dims and locks its four parameter knobs, which do nothing until a type is chosen.
//
// Nothing dims until the value is KNOWN: received from the GAIA (a read or an echo, which raises
// onParameterReceived even when the value matches the default) or changed here. Every one of these
// defaults to OFF in the profile, so dimming from the defaults would open an unconnected panel with
// the whole instrument greyed out, which says less than it seems to.
//
// A tone row is dimmed, not locked: you can still set a tone up before switching it on. Its
// controls take their opacity from the script, so the section frames and printed captions dim with
// the knobs. The script only writes when something changes, because a write takes a caption out of
// the baked scenery layer.
export const DIMMED = 0.35;

export function activeStateScript(config) {
  return `// Dim switched-off tones and lock effect knobs while TYPE is OFF.
// Generated by tools/scripts/gaia-panel/active-state.mjs. Controls are addressed by ID.

var CONFIG = ${JSON.stringify(config, null, 2)};

function isOn(v) { return v === true || v === 1 || v === "1" || String(v).toLowerCase() === "on"; }
function isOff(v) { return v === false || v === 0 || v === "0" || String(v).toLowerCase() === "off"; }

function opacity(id, value) {
  var current = get(id + ".opacity");
  if ((current == null ? 1 : Number(current)) !== value) set(id + ".opacity", value);
}
function enabled(id, value) {
  var current = get(id + ".enabled");
  if ((current == null ? true : current !== false) !== value) set(id + ".enabled", value);
}

function showTone(tone, on) {
  for (var i = 0; i < tone.members.length; i++) opacity(tone.members[i], on ? 1 : CONFIG.dimmed);
}
function showEffect(effect, off) {
  for (var i = 0; i < effect.knobs.length; i++) {
    enabled(effect.knobs[i], !off);
    opacity(effect.knobs[i], off ? CONFIG.dimmed : 1);
  }
  for (var j = 0; j < effect.captions.length; j++) opacity(effect.captions[j], off ? CONFIG.dimmed : 1);
}

function onPanelLoad() {
  // Unknown until told: undo anything a saved panel carried over, then wait for a real value.
  CONFIG.tones.forEach(function (tone) {
    showTone(tone, true);
    watch(tone.switchId + ".value", function () { showTone(tone, isOn(get(tone.switchId))); });
  });
  CONFIG.effects.forEach(function (effect) {
    showEffect(effect, false);
    watch(effect.typeId + ".value", function () { showEffect(effect, isOff(get(effect.typeId))); });
  });
  on("*", "onParameterReceived", function (info) {
    if (!info || (info.role && info.role !== CONFIG.role)) return;
    CONFIG.tones.forEach(function (tone) { if (info.parameter === tone.parameter) showTone(tone, isOn(info.value)); });
    CONFIG.effects.forEach(function (effect) { if (info.parameter === effect.parameter) showEffect(effect, isOff(info.value)); });
  });
}
`;
}

export function applyActiveState(panel, role) {
  const all = flatControls(panel.controls);
  const named = name => all.find(c => c._children.Core.name === name);
  const id = name => {
    const c = named(name);
    if (!c) throw new Error(`Missing ${name}`);
    return c._children.Core.id;
  };
  const rect = c => c._children.Transform;
  const rows = name => panel.controls.filter(c => c._children.Core.name === name).sort((a, b) => rect(a).y - rect(b).y);
  const lfo = rows('box_LFO'), mod = rows('box_MOD LFO');
  const tones = [1, 2, 3].map(tone => {
    const left = rect(lfo[tone - 1]), right = rect(mod[tone - 1]);
    const bounds = { x0: left.x, x1: right.x + right.width, y0: left.y, y1: left.y + left.height };
    // Everything drawn inside the row, frames and captions included, but never the TONE buttons
    // to its left: TONE n ON is how you bring the row back.
    const members = panel.controls.filter(c => {
      const t = rect(c), cx = t.x + t.width / 2, cy = t.y + t.height / 2;
      return cx >= bounds.x0 && cx <= bounds.x1 && cy >= bounds.y0 && cy <= bounds.y1;
    }).map(c => c._children.Core.id);
    return { parameter: `common.tone${tone}Switch`, switchId: id(`common.tone${tone}Switch`), members };
  });
  const effects = ['distortion', 'flanger', 'delay', 'reverb'].map(effect => ({
    parameter: `${effect}.type`,
    typeId: id(`${effect}.type`),
    knobs: [1, 2, 3, 4].map(i => id(`${effect}.parameter${i}`)),
    captions: [1, 2, 3, 4].map(i => id(`${effect}.parameter${i}.caption`)),
  }));
  const script = createScript({
    id: 'gaia_active_state', name: 'Dim what is switched off', language: 'javascript',
    scope: 'panel', event: 'onPanelLoad', target: '*',
    description: 'Dims a switched-off tone row and locks effect knobs while TYPE is OFF, once the value is known. Sends no MIDI.',
    source: activeStateScript({ role, dimmed: DIMMED, tones, effects }),
  });
  const existing = (panel.scripts ?? []).findIndex(s => s.id === script.id);
  if (existing < 0) panel.scripts = [...(panel.scripts ?? []), script];
  else panel.scripts[existing] = script;
  return panel;
}
