// effect-probe.mjs — ask the instrument which addresses its effect knobs actually drive.
//
// WHY THIS EXISTS. effect-parameters.mjs has the effect TYPES (those come from the profile's own
// choice lists) and no parameter NAMES, because the MIDI implementation does not print them: every
// effect block is 32 slots called "MFX Parameter 1..32", all with the same container range. Which
// slots a given type uses, and what they mean, is in the owner's manual.
//
// But half of that question does not need the manual at all. Which SLOT each knob drives is a fact
// about the hardware, and the hardware will tell you: dump the block, move one knob, dump again,
// and exactly one of the 32 values will have changed. That is more trustworthy than a transcription
// anyway — it is the instrument answering about itself.
//
// WHAT THE KNOBS ACTUALLY ARE, which is not obvious and which this file exists to encode. The GAIA
// has TWO physical knobs for effects, not four. The four parameters are reached as:
//
//     CONTROL 1   turn the CONTROL 1 knob
//     CONTROL 2   SHIFT (cancel) + turn the CONTROL 1 knob
//     CONTROL 3   SHIFT (cancel) + turn the LEVEL knob
//     LEVEL       turn the LEVEL knob
//
// So a procedure that says "now turn CONTROL 2" is describing a knob that does not exist. The
// prompts below name the real gesture.
//
// AND IT TESTS AN ASSUMPTION NOBODY CHECKED. The panel shows MFX Parameter 1..4 — the first four
// addresses — on the assumption that those are the four the knobs drive. Nothing establishes that.
// If a type's knobs turn out to drive, say, slots 1, 2, 3 and 17, the panel is currently showing
// three live parameters and one dead one, and the probe is what would reveal it.
//
// DISABLED IN THE SHIPPED PANEL. It is a diagnostic, not a feature: enable it in the Scripts tab
// when you have the instrument in front of you, run it, and switch it off again.

/** The four parameter slots the panel shows per effect. */
export const PROBE_SLOTS = 4;

// Every slot in a block, which is what makes the probe able to find one outside the first four.
// NOT a constant: distortion carries 32 and the other three carry 20, so a hardcoded 32 would have
// the probe reading twelve addresses the flanger does not have and calling every one of them
// "unchanged" — a clean-looking result from a question that was never asked.

/**
 * The gestures, in the panel's left-to-right order.
 *
 * `label` is what the caption would read; `how` is what a person does to the instrument. Kept
 * together because the whole point of the probe is to connect the two.
 */
export const KNOB_GESTURES = [
  { label: 'CONTROL 1', how: 'turn the CONTROL 1 knob' },
  { label: 'CONTROL 2', how: 'hold SHIFT (cancel) and turn the CONTROL 1 knob' },
  { label: 'CONTROL 3', how: 'hold SHIFT (cancel) and turn the LEVEL knob' },
  { label: 'LEVEL', how: 'turn the LEVEL knob' },
];

/**
 * A panel script that walks the four gestures for one effect block and reports what moved.
 *
 * `blocks` maps an effect key to { requestId, parameterPrefix, slots } — the RQ1 request that
 * fetches the whole block, the parameter-id stem its slots share, and how many there are.
 */
export function effectProbeScript(blocks) {
  const table = {};
  for (const [effect, block] of Object.entries(blocks ?? {})) {
    table[effect] = {
      request: block.requestId,
      prefix: block.parameterPrefix,
      slots: Number(block.slots) > 0 ? Math.round(Number(block.slots)) : 0,
    };
  }
  if (Object.keys(table).length === 0) return null;

  return `// Which address does each effect knob drive? Ask the instrument.
//
// Generated by tools/scripts/gaia-panel/effect-probe.mjs. A DIAGNOSTIC — leave it disabled unless
// you are filling in EFFECT_PARAMETER_NAMES, and switch it off again afterwards.
//
// HOW TO USE IT, from the script console:
//
//   1. On the GAIA, select the effect and the TYPE you are mapping (e.g. DISTORTION -> DIST).
//   2. run("fxProbe", "distortion")        reads the block and remembers it
//   3. Move ONE knob, as the console tells you. The GAIA reaches four parameters with two knobs:
//        CONTROL 1  turn CONTROL 1
//        CONTROL 2  SHIFT (cancel) + turn CONTROL 1
//        CONTROL 3  SHIFT (cancel) + turn LEVEL
//        LEVEL      turn LEVEL
//   4. run("fxMark", "CONTROL 1")          reads again and says which slot changed
//   5. Repeat 3-4 for the other three, then run("fxReport") for the summary.
//
// If nothing is reported as changed, the instrument is probably not transmitting panel moves —
// check its MIDI transmit / "Tx Edit" setting before concluding the knob is dead.

var BLOCKS = ${JSON.stringify(table, null, 2)};

var current = null;      // { effect, values: [...] }
var found = {};          // gesture label -> slot number

function readBlock(effect) {
  var block = BLOCKS[effect];
  var values = [];
  for (var i = 1; i <= block.slots; i++) {
    values.push(ce.device.read(block.prefix + i));
  }
  return values;
}

function changedSlots(before, after) {
  var moved = [];
  for (var i = 0; i < before.length; i++) {
    if (before[i] !== after[i]) moved.push({ slot: i + 1, from: before[i], to: after[i] });
  }
  return moved;
}

function fxProbe(effect) {
  var key = String(effect || "distortion");
  if (!BLOCKS[key]) {
    log("fxProbe: no block called " + key + " — one of: " + Object.keys(BLOCKS).join(", "));
    return;
  }
  ce.device.requestDump(BLOCKS[key].request, function (values, info) {
    if (!info.ok) {
      log("fxProbe: no dump arrived (" + info.error + "). Is the GAIA connected and its ID right?");
      return;
    }
    current = { effect: key, values: readBlock(key) };
    found = {};
    log("fxProbe: " + key + " read (" + BLOCKS[key].slots + " slots). Now move ONE knob, then "
      + "run(\\"fxMark\\", \\"CONTROL 1\\").");
    log("  CONTROL 1 = turn CONTROL 1 · CONTROL 2 = SHIFT+CONTROL 1 · "
      + "CONTROL 3 = SHIFT+LEVEL · LEVEL = turn LEVEL");
  });
}

function fxMark(gesture) {
  if (!current) { log("fxMark: run(\\"fxProbe\\", \\"distortion\\") first."); return; }
  var name = String(gesture || "?");
  ce.device.requestDump(BLOCKS[current.effect].request, function (values, info) {
    if (!info.ok) { log("fxMark: no dump arrived (" + info.error + ")"); return; }
    var after = readBlock(current.effect);
    var moved = changedSlots(current.values, after);
    current.values = after;

    if (moved.length === 0) {
      log("fxMark(" + name + "): nothing changed. Move the knob further, or check the GAIA's "
        + "MIDI transmit setting.");
      return;
    }
    if (moved.length > 1) {
      var all = moved.map(function (m) { return m.slot; }).join(", ");
      log("fxMark(" + name + "): " + moved.length + " slots moved (" + all + ") — move one knob at "
        + "a time, and re-run fxProbe to re-baseline.");
      return;
    }
    found[name] = moved[0].slot;
    log("fxMark(" + name + ") -> MFX Parameter " + moved[0].slot
      + "  (" + moved[0].from + " -> " + moved[0].to + ")");
  });
}

function fxReport() {
  if (!current) { log("fxReport: nothing probed yet."); return; }
  var order = ${JSON.stringify(KNOB_GESTURES.map((g) => g.label))};
  var line = [];
  for (var i = 0; i < order.length; i++) {
    var slot = found[order[i]];
    line.push(order[i] + " = " + (slot ? "MFX Parameter " + slot : "?"));
  }
  log("fxReport " + current.effect + ": " + line.join(" · "));
  // The panel shows slots 1..${PROBE_SLOTS}. If a knob drives anything else, the panel is showing a
  // parameter nothing turns — worth knowing before the names go in.
  var outside = [];
  for (var j = 0; j < order.length; j++) {
    var s = found[order[j]];
    if (s && s > ${PROBE_SLOTS}) outside.push(order[j] + " -> " + s);
  }
  if (outside.length) {
    log("fxReport: these are OUTSIDE the four the panel shows — " + outside.join(", ")
      + ". layout.mjs is displaying the wrong slots for this type.");
  }
}

function onPanelLoad() {
  defineAction("fxProbe", fxProbe);
  defineAction("fxMark", fxMark);
  defineAction("fxReport", fxReport);
  log("Effect probe ready. run(\\"fxProbe\\", \\"distortion\\") to begin.");
}
`;
}
