import { noteName } from './pianoGeometry.js';

// Describe only facts available from the host. A quiet meter is not a fault, and the
// global MIDI monitor cannot diagnose notes generated by a clip or another part.
export function hostPartIssues(state, part, recentNote = null) {
  if (!part) return [];
  const issues = [];
  const add = (id, icon, detail, target, existing = false) =>
    issues.push({ id, icon, detail, target, existing });
  if (part.unresolved) add('missing', 'plug', 'Instrument is missing or has not loaded.', 'health', true);
  if (!part.enabled) add('off', 'level', 'Part is switched off.', 'part', true);
  if (part.mute) add('mute', 'level', 'Part is muted.', 'mixer', true);
  if (!part.hasInstrument && !part.hardware) return issues;

  if (part.hardware && part.midiOutError)
    add('midi-output', 'plug', part.midiOutError, 'routing');
  const gone = (state.reliability?.midi?.issues ?? []).filter(issue =>
    issue.kind === 'inputGone' && issue.parts?.some(p => p.partId === part.partId));
  if (gone.length)
    add('midi-input', 'plug', `MIDI input disconnected: ${[...new Set(gone.map(i => i.device))].join(', ')}.`, 'devices');
  const failed = (state.reliability?.automaticFailover?.events ?? []).find(event =>
    !event.effect && event.targetId === part.partId && event.state !== 'recovered');
  if (failed) add('processor', 'plug', `Instrument recovery: ${failed.error || failed.state}.`, 'health');

  // Mute and Off already have visible controls. Do not stack secondary audio indicators
  // on those rows. These describe the audio path, including hardware returns, not MIDI out.
  if (!part.enabled || part.mute) return issues;
  const solos = (state.rack?.parts ?? []).filter(p => p.solo && p.partId !== part.partId);
  if (!part.solo && solos.length)
    add('solo-other', 'solo', `Part audio suppressed by Solo on ${solos.map(p => p.pluginName || p.midiOutputName || 'another part').join(', ')}.`, 'mixer');
  else if (part.volume === 0)
    add('level-zero', 'level', 'Part audio fader is at zero.', 'mixer');

  if (recentNote?.partId !== part.partId || state.rack?.focusedPartId !== part.partId
      || part.midiSourcePartId || !(recentNote.value > 0) || !(recentNote.channel > 0)) return issues;
  const filters = [];
  if (part.channel > 0 && part.channel !== recentNote.channel)
    filters.push(`channel ${recentNote.channel}; this part accepts channel ${part.channel}`);
  if (recentNote.note < part.keyLow || recentNote.note > part.keyHigh)
    filters.push(`${noteName(recentNote.note)} outside ${noteName(part.keyLow)}–${noteName(part.keyHigh)}`);
  if (recentNote.value < part.velocityLow || recentNote.value > part.velocityHigh)
    filters.push(`velocity ${recentNote.value} outside ${part.velocityLow}–${part.velocityHigh}`);
  if (filters.length)
    add('zone', 'filter', `Last monitored input${recentNote.device ? ` from ${recentNote.device}` : ''}: ${filters.join('; ')}.`, 'zone');
  return issues;
}
