// The catalogue: the remaining control sets from the mockup boards (docs/design/control-sets.md),
// converted from the boards' own palettes and part choices by a one-off script and then kept here
// as source. Edit by hand from here on; there is no generator to re-run.
//
// Each set is what every catalogue set is: forty colour roles, a lamp, a family patch (a knob's
// cap and pointer, the buttons' corners and finish — models/controlSetRecipes.js) and what it
// asks of the panel. Tolex and Machined, the pilot, are in models/pilotControlSets.js; Graphite,
// Ember and Ivory are in models/controlSets.js, and CATALOG_SET_EXTRAS gives the last two the
// families and panels their boards showed.

import { buttonFamily, knobFamily, mergeFamilies, panelSpec } from './controlSetRecipes.js';

const LAMP = { azimuth: 225, elevation: 48 };

export const CATALOG_CONTROL_SETS = [
  {
    id: "console",
    name: "Console",
    description: "Brushed aluminium desk. Black skirted knobs, long-throw faders with a grooved cap, LED toggles.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 64, pointer: "line", pointerWidth: 3, pointerLength: 82, track: 8, capMaterial: ["brushed", 60, 80] }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["brushed", 50, 60] })),
    panel: panelSpec("FF5E6166", "brushed", 70, 50),
    tokens: {
      "surface": "FF3B3D42",
      "surface.hover": "FF4A4D53",
      "surface.pressed": "FF2A2C30",
      "surface.checked": "FF2F3136",
      "surface.mixed": "FFB3832E",
      "control.button": "FF3B3D42",
      "control.button.hover": "FF4B4D51",
      "control.button.pressed": "FF35373B",
      "control.field": "FF1F2023",
      "control.field.hover": "FF2A2B2E",
      "control.field.active": "FF56585B",
      "control.select": "FF2F3136",
      "control.select.hover": "FF404146",
      "control.select.pressed": "FF2B2D32",
      "control.track": "FF2A2C30",
      "control.track.edge": "551A1B1E",
      "control.fill": "FFD8DADF",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FF9BA1A8",
      "control.range.hot": "FFAAAFB5",
      "control.cap": "FF5B5E63",
      "control.cap.hot": "FF6B6E73",
      "control.cap.edge": "992A2A2A",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FFF2F2F2",
      "control.tick": "CCF4F4F4",
      "control.tick.minor": "88F4F4F4",
      "accent": "FFD8DADF",
      "accent.hot": "FFFF3B30",
      "text.primary": "FFF4F4F4",
      "text.label": "FFF4F4F4",
      "text.muted": "FFD7D9DD",
      "text.focus": "FFFFFFFF",
      "text.inverse": "FFFFFFFF",
      "border": "661E1F22",
      "border.surface": "661E1F22",
      "border.field": "661E1F22",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "Dark glass and light. Arcs glow, caps glow, the accent is the whole personality. The modern plug-in look.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, pointer: "line", pointerWidth: 3, pointerLength: 84, track: 6, capMaterial: ["glass", 60, 140] }), buttonFamily({ radius: 10 })),
    panel: panelSpec("FF0E1116"),
    tokens: {
      "surface": "FF1B222B",
      "surface.hover": "FF243040",
      "surface.pressed": "FF141A22",
      "surface.checked": "FF6EF2E8",
      "surface.mixed": "FFCC9356",
      "control.button": "FF1B222B",
      "control.button.hover": "FF2D343C",
      "control.button.pressed": "FF181F27",
      "control.field": "FF0B0E13",
      "control.field.hover": "FF171A1F",
      "control.field.active": "FF295253",
      "control.select": "FF161C24",
      "control.select.hover": "FF292E36",
      "control.select.pressed": "FF141A21",
      "control.track": "FF1B222B",
      "control.track.edge": "552A3440",
      "control.fill": "FF6EF2E8",
      "control.fill.hot": "FFB6FFFA",
      "control.range": "FF9A8CFF",
      "control.range.hot": "FFA99DFF",
      "control.cap": "FF1B222B",
      "control.cap.hot": "FF323840",
      "control.cap.edge": "990E1116",
      "control.cap.start": "FFFFB86C",
      "control.cap.end": "FF9A8CFF",
      "control.marker": "FF6EF2E8",
      "control.tick": "CC8FA3B8",
      "control.tick.minor": "888FA3B8",
      "accent": "FF6EF2E8",
      "accent.hot": "FFB6FFFA",
      "text.primary": "FFEAF2FF",
      "text.label": "FFEAF2FF",
      "text.muted": "FF8FA3B8",
      "text.focus": "FFB6FFFA",
      "text.inverse": "FF0E1116",
      "border": "662F3B49",
      "border.surface": "662F3B49",
      "border.field": "662F3B49",
      "border.mixed": "FFFFB86C",
    },
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Line work only. One ink, one paper, hairline strokes on a faint grid. The schematic, for panels that are documents.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, capEdgeWidth: 1.5, pointer: "line", pointerWidth: 1.5, pointerLength: 90, track: 2 }), buttonFamily({ radius: 2, border: 1 })),
    panel: panelSpec("FF14243A"),
    tokens: {
      "surface": "FF14243A",
      "surface.hover": "FF1D3252",
      "surface.pressed": "FF0E1A2C",
      "surface.checked": "FFDCE8F5",
      "surface.mixed": "FFC29D4E",
      "control.button": "FF14243A",
      "control.button.hover": "FF27364A",
      "control.button.pressed": "FF122034",
      "control.field": "FF0E1A2C",
      "control.field.hover": "FF1A2537",
      "control.field.active": "FF4C5868",
      "control.select": "FF14243A",
      "control.select.hover": "FF27364A",
      "control.select.pressed": "FF122135",
      "control.track": "FF22375A",
      "control.track.edge": "55DCE8F5",
      "control.fill": "FFDCE8F5",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FF7FA6D6",
      "control.range.hot": "FF92B3DC",
      "control.cap": "FF14243A",
      "control.cap.hot": "FF2C3A4E",
      "control.cap.edge": "99DCE8F5",
      "control.cap.start": "FFF2C462",
      "control.cap.end": "FF8FE3B0",
      "control.marker": "FFDCE8F5",
      "control.tick": "CCDCE8F5",
      "control.tick.minor": "88DCE8F5",
      "accent": "FFDCE8F5",
      "accent.hot": "FFFFD166",
      "text.primary": "FFDCE8F5",
      "text.label": "FFDCE8F5",
      "text.muted": "FF9DB4CF",
      "text.focus": "FFFFD166",
      "text.inverse": "FF14243A",
      "border": "66DCE8F5",
      "border.surface": "66DCE8F5",
      "border.field": "669DB4CF",
      "border.mixed": "FFF2C462",
    },
  },
  {
    id: "walnut",
    name: "Walnut",
    description: "Hi-fi from the seventies. Walnut panel, brass bezels, cream dials with a black hairline. Quiet, expensive.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capEdgeWidth: 2.5, pointer: "line", pointerWidth: 1.5, pointerLength: 84, track: 3, readoutFill: "{control.marker}" }), buttonFamily({ radius: 5, border: 1, buttonMaterial: ["brushed", 40, 60] })),
    panel: panelSpec("FF4A3226", "brushed", 50, 30, 60),
    tokens: {
      "surface": "FF5C4033",
      "surface.hover": "FF6B4B3C",
      "surface.pressed": "FF3F2B21",
      "surface.checked": "FFB08D3C",
      "surface.mixed": "FFB3832E",
      "control.button": "FF5C4033",
      "control.button.hover": "FF694F43",
      "control.button.pressed": "FF533A2E",
      "control.field": "FF1E140F",
      "control.field.hover": "FF29201B",
      "control.field.active": "FF564426",
      "control.select": "FF3F2B21",
      "control.select.hover": "FF4E3C33",
      "control.select.pressed": "FF3A281E",
      "control.track": "FF2B1E17",
      "control.track.edge": "551A110C",
      "control.fill": "FFD9B45B",
      "control.fill.hot": "FFF2D07A",
      "control.range": "FFB08D3C",
      "control.range.hot": "FFBC9E59",
      "control.cap": "FFFFF7E6",
      "control.cap.hot": "FFFFF8E8",
      "control.cap.edge": "996B5A2E",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF8FB07A",
      "control.marker": "FF3A2A10",
      "control.tick": "CCF3E7CF",
      "control.tick.minor": "88F3E7CF",
      "accent": "FFD9B45B",
      "accent.hot": "FFF2D07A",
      "text.primary": "FFF6ECD8",
      "text.label": "FFF6ECD8",
      "text.muted": "FFCDB99A",
      "text.focus": "FFFFF3D6",
      "text.inverse": "FF2B1E17",
      "border": "662B1E17",
      "border.surface": "662B1E17",
      "border.field": "662B1E17",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "soft",
    name: "Soft",
    description: "Pale, raised and quiet. Everything sits a few pixels off a light grey panel with a soft shadow; one violet accent.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 76, capEdgeWidth: 0.5, pointer: "line", pointerWidth: 3, pointerLength: 70, track: 5 }), buttonFamily({ radius: 12, border: 1 })),
    panel: panelSpec("FFE8EAEE"),
    tokens: {
      "surface": "FFF7F8FA",
      "surface.hover": "FFFFFFFF",
      "surface.pressed": "FFE3E6EB",
      "surface.checked": "FF5B5BD6",
      "surface.mixed": "FFB67B25",
      "control.button": "FFF7F8FA",
      "control.button.hover": "FFF8F9FA",
      "control.button.pressed": "FFDEDFE1",
      "control.field": "FFFFFFFF",
      "control.field.hover": "FFFFFFFF",
      "control.field.active": "FFCECEF3",
      "control.select": "FFFFFFFF",
      "control.select.hover": "FFFFFFFF",
      "control.select.pressed": "FFEBEBEB",
      "control.track": "FFD3D7DE",
      "control.track.edge": "55D3D7DE",
      "control.fill": "FF5B5BD6",
      "control.fill.hot": "FF7B7BEC",
      "control.range": "FFA9A9F0",
      "control.range.hot": "FFB6B6F2",
      "control.cap": "FFF4F5F7",
      "control.cap.hot": "FFF5F6F8",
      "control.cap.edge": "99FFFFFF",
      "control.cap.start": "FFE39A2E",
      "control.cap.end": "FF3BAF7E",
      "control.marker": "FF5B5BD6",
      "control.tick": "CC7C8290",
      "control.tick.minor": "887C8290",
      "accent": "FF5B5BD6",
      "accent.hot": "FF3E3EC4",
      "text.primary": "FF262A33",
      "text.label": "FF262A33",
      "text.muted": "FF6E7482",
      "text.focus": "FF3E3EC4",
      "text.inverse": "FFFFFFFF",
      "border": "66DFE2E8",
      "border.surface": "66DFE2E8",
      "border.field": "66DFE2E8",
      "border.mixed": "FFE39A2E",
    },
  },
  {
    id: "phosphor",
    name: "Phosphor",
    description: "Hardware from a rack: LED rings, segmented meters, one green phosphor on matte black. Nothing is drawn that a real front panel could not light up.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 0, pointer: "dot", track: 6 }), buttonFamily({ radius: 2 })),
    panel: panelSpec("FF0B0D0B"),
    tokens: {
      "surface": "FF151815",
      "surface.hover": "FF1F241F",
      "surface.pressed": "FF0F110F",
      "surface.checked": "FF123D22",
      "surface.mixed": "FFCC8D1A",
      "control.button": "FF151815",
      "control.button.hover": "FF282A28",
      "control.button.pressed": "FF131613",
      "control.field": "FF0B0D0B",
      "control.field.hover": "FF171917",
      "control.field.active": "FF19562C",
      "control.select": "FF111311",
      "control.select.hover": "FF242624",
      "control.select.pressed": "FF101110",
      "control.track": "FF1F241F",
      "control.track.edge": "552C312C",
      "control.fill": "FF39FF7A",
      "control.fill.hot": "FFB8FFD2",
      "control.range": "FF1FA35A",
      "control.range.hot": "FF41B173",
      "control.cap": "FF39FF7A",
      "control.cap.hot": "FF4DFF87",
      "control.cap.edge": "990B0D0B",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF39FF7A",
      "control.marker": "FF5A6A5A",
      "control.tick": "CC5A6A5A",
      "control.tick.minor": "885A6A5A",
      "accent": "FF39FF7A",
      "accent.hot": "FF39FF7A",
      "text.primary": "FFD6FFE3",
      "text.label": "FFD6FFE3",
      "text.muted": "FF7FA88C",
      "text.focus": "FFB8FFD2",
      "text.inverse": "FF0B0D0B",
      "border": "662C312C",
      "border.surface": "662C312C",
      "border.field": "662C312C",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "pop",
    name: "Pop",
    description: "Thick black outlines, saturated fills, big round caps. A toy synth's confidence \u2014 readable from across the room.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 78, capEdge: "{control.marker}", capEdgeWidth: 3, pointer: "dot", dotSize: 24, track: 7 }), buttonFamily({ radius: 10, border: 3 })),
    panel: panelSpec("FFF6D96B"),
    tokens: {
      "surface": "FFFFFFFF",
      "surface.hover": "FFFFF3E0",
      "surface.pressed": "FFFFD9C9",
      "surface.checked": "FFFF6B5B",
      "surface.mixed": "FFCC8D1A",
      "control.button": "FFFFFFFF",
      "control.button.hover": "FFFFFFFF",
      "control.button.pressed": "FFE6E6E6",
      "control.field": "FFFFFFFF",
      "control.field.hover": "FFFFFFFF",
      "control.field.active": "FFFFD3CE",
      "control.select": "FFFFFFFF",
      "control.select.hover": "FFFFFFFF",
      "control.select.pressed": "FFEBEBEB",
      "control.track": "FFFFFFFF",
      "control.track.edge": "551B1B1B",
      "control.fill": "FFFF6B5B",
      "control.fill.hot": "FFFF8A7D",
      "control.range": "FF5BC8FF",
      "control.range.hot": "FF74D0FF",
      "control.cap": "FFFFFFFF",
      "control.cap.hot": "FFFFFFFF",
      "control.cap.edge": "991B1B1B",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF3BC46E",
      "control.marker": "FF1B1B1B",
      "control.tick": "CC1B1B1B",
      "control.tick.minor": "881B1B1B",
      "accent": "FFFF6B5B",
      "accent.hot": "FF1B1B1B",
      "text.primary": "FF1B1B1B",
      "text.label": "FF1B1B1B",
      "text.muted": "FF5A4A1E",
      "text.focus": "FF1B1B1B",
      "text.inverse": "FFFFFFFF",
      "border": "661B1B1B",
      "border.surface": "661B1B1B",
      "border.field": "661B1B1B",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "carbon",
    name: "Carbon",
    description: "Pro gear. Carbon-weave panel, rubberised black knobs with a grip ring and a single orange dot. Chamfered, dense, serious.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capMaterial: ["rubber", 80, 0], pointer: "line", pointerWidth: 3, pointerLength: 80, track: 3 }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["blast", 50, 40] })),
    panel: panelSpec("FF1C1E21", "leather", 60, 20, 140),
    tokens: {
      "surface": "FF2A2D32",
      "surface.hover": "FF343840",
      "surface.pressed": "FF1C1E21",
      "surface.checked": "FFFF7A1A",
      "surface.mixed": "FFCC9B56",
      "control.button": "FF2A2D32",
      "control.button.hover": "FF3B3E42",
      "control.button.pressed": "FF26282D",
      "control.field": "FF111214",
      "control.field.hover": "FF1D1E20",
      "control.field.active": "FF583116",
      "control.select": "FF22252A",
      "control.select.hover": "FF34363B",
      "control.select.pressed": "FF1F2227",
      "control.track": "FF2A2D32",
      "control.track.edge": "550F1012",
      "control.fill": "FFFF7A1A",
      "control.fill.hot": "FFFFA35C",
      "control.range": "FF8A4A1A",
      "control.range.hot": "FF9C653C",
      "control.cap": "FF111214",
      "control.cap.hot": "FF292A2C",
      "control.cap.edge": "990A0A0B",
      "control.cap.start": "FFFFC26B",
      "control.cap.end": "FFB8C4CC",
      "control.marker": "FFFF7A1A",
      "control.tick": "CC8C939C",
      "control.tick.minor": "888C939C",
      "accent": "FFFF7A1A",
      "accent.hot": "FFFFA35C",
      "text.primary": "FFE8ECF0",
      "text.label": "FFE8ECF0",
      "text.muted": "FF8C939C",
      "text.focus": "FFFFC26B",
      "text.inverse": "FF111214",
      "border": "660F1012",
      "border.surface": "660F1012",
      "border.field": "660F1012",
      "border.mixed": "FFFFC26B",
    },
  },
  {
    id: "atelier",
    name: "Atelier",
    description: "Rams. Warm light-grey aluminium, flat pale knobs with one coloured dot, ticks but no arcs, tiny accents of orange and green. Less than you expect.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, pointer: "line", pointerWidth: 3, pointerLength: 80, track: 4, trackOpacity: 0.35 }), buttonFamily({ radius: 4 })),
    panel: panelSpec("FFD9D9D4"),
    tokens: {
      "surface": "FFEDEDEA",
      "surface.hover": "FFF6F6F3",
      "surface.pressed": "FFD0D0CB",
      "surface.checked": "FF1C1C1A",
      "surface.mixed": "FFBA470A",
      "control.button": "FFEDEDEA",
      "control.button.hover": "FFEEEEEC",
      "control.button.pressed": "FFD5D5D3",
      "control.field": "FFF6F6F3",
      "control.field.hover": "FFF6F6F4",
      "control.field.active": "FFB5B5B2",
      "control.select": "FFF6F6F3",
      "control.select.hover": "FFF7F7F4",
      "control.select.pressed": "FFE2E2E0",
      "control.track": "FFB9B9B3",
      "control.track.edge": "55B9B9B3",
      "control.fill": "FF1C1C1A",
      "control.fill.hot": "FFE8590C",
      "control.range": "FF8C8C86",
      "control.range.hot": "FF9D9D98",
      "control.cap": "FFEDEDEA",
      "control.cap.hot": "FFEFEFEC",
      "control.cap.edge": "99B9B9B3",
      "control.cap.start": "FFE8590C",
      "control.cap.end": "FF3E8E4E",
      "control.marker": "FF1C1C1A",
      "control.tick": "CC1C1C1A",
      "control.tick.minor": "881C1C1A",
      "accent": "FF1C1C1A",
      "accent.hot": "FFE8590C",
      "text.primary": "FF1C1C1A",
      "text.label": "FF1C1C1A",
      "text.muted": "FF5E5E5A",
      "text.focus": "FFE8590C",
      "text.inverse": "FFFFFFFF",
      "border": "66B9B9B3",
      "border.surface": "66B9B9B3",
      "border.field": "66B9B9B3",
      "border.mixed": "FFE8590C",
    },
  },
  {
    id: "chrome",
    name: "Chrome",
    description: "The 2000s plug-in, unashamed. Mirror-polished knobs, glassy buttons with a highlight, a deep blue-black panel. Skeuomorphic and proud of it.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capMaterial: ["glass", 50, 180], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5, readoutFill: "{control.marker}" }), buttonFamily({ radius: 6, border: 1, buttonMaterial: ["glass", 40, 120] })),
    panel: panelSpec("FF10151F"),
    tokens: {
      "surface": "FF2A3544",
      "surface.hover": "FF34425A",
      "surface.pressed": "FF1A2230",
      "surface.checked": "FF1E5F86",
      "surface.mixed": "FFCC8D1A",
      "control.button": "FF2A3544",
      "control.button.hover": "FF3B4553",
      "control.button.pressed": "FF26303D",
      "control.field": "FF0A0E14",
      "control.field.hover": "FF161A20",
      "control.field.active": "FF15455A",
      "control.select": "FF1E2733",
      "control.select.hover": "FF303843",
      "control.select.pressed": "FF1C242F",
      "control.track": "FF1E2733",
      "control.track.edge": "550A0E14",
      "control.fill": "FF2FC4FF",
      "control.fill.hot": "FF8EE0FF",
      "control.range": "FF7FA6FF",
      "control.range.hot": "FF92B3FF",
      "control.cap": "FFB8C0C8",
      "control.cap.hot": "FFBFC6CE",
      "control.cap.edge": "993A424B",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF4CD98A",
      "control.marker": "FF2B2F33",
      "control.tick": "CC9AA6B4",
      "control.tick.minor": "889AA6B4",
      "accent": "FF2FC4FF",
      "accent.hot": "FF8EE0FF",
      "text.primary": "FFEEF3F8",
      "text.label": "FFEEF3F8",
      "text.muted": "FF9AA6B4",
      "text.focus": "FF8EE0FF",
      "text.inverse": "FF0E1B2E",
      "border": "660A0E14",
      "border.surface": "660A0E14",
      "border.field": "660A0E14",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "frost",
    name: "Frost",
    description: "Frosted glass over a colour field. Translucent white controls, thin bright edges, a violet-to-teal panel behind. Light, airy, current.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, capFill: "66FFFFFF", capEdge: "AAFFFFFF", pointer: "line", pointerWidth: 3, pointerLength: 80, track: 5 }), buttonFamily({ radius: 14, border: 1, text: "{text.inverse}", fieldText: "{text.inverse}" })),
    panel: panelSpec("FF6A5BD6"),
    tokens: {
      "surface": "38FFFFFF",
      "surface.hover": "55FFFFFF",
      "surface.pressed": "22FFFFFF",
      "surface.checked": "FFFFFFFF",
      "surface.mixed": "FFCCB562",
      "control.button": "38FFFFFF",
      "control.button.hover": "55FFFFFF",
      "control.button.pressed": "22FFFFFF",
      "control.field": "33FFFFFF",
      "control.field.hover": "44FFFFFF",
      "control.field.active": "55FFFFFF",
      "control.select": "38FFFFFF",
      "control.select.hover": "55FFFFFF",
      "control.select.pressed": "22FFFFFF",
      "control.track": "55FFFFFF",
      "control.track.edge": "55FFFFFF",
      "control.fill": "FFFFE27A",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FFFFB6E6",
      "control.range.hot": "FFFFC1EA",
      "control.cap": "CCFFFFFF",
      "control.cap.hot": "FFFFFFFF",
      "control.cap.edge": "99FFFFFF",
      "control.cap.start": "FFFFE27A",
      "control.cap.end": "FFB6FFE8",
      "control.marker": "FFFFFFFF",
      "control.tick": "CCFFFFFF",
      "control.tick.minor": "88FFFFFF",
      "accent": "FFFFE27A",
      "accent.hot": "FFFFE27A",
      "text.primary": "FFFFFFFF",
      "text.label": "FFFFFFFF",
      "text.muted": "FFEAE6FF",
      "text.focus": "FFFFE27A",
      "text.inverse": "FF2B2270",
      "border": "88FFFFFF",
      "border.surface": "AAFFFFFF",
      "border.field": "88FFFFFF",
      "border.mixed": "FFFFE27A",
    },
  },
  {
    id: "rackmount",
    name: "Rackmount",
    description: "One rack unit of outboard. Silver faceplate with rack ears and screws, black knobs on silver bevels, illuminated square pushbuttons, a needle VU.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, capEdgeWidth: 2, pointer: "line", pointerWidth: 3, pointerLength: 80, track: 6, readoutFill: "{control.marker}" }), buttonFamily({ radius: 2, border: 1, buttonMaterial: ["brushed", 50, 60], text: "FFFFFFFF", fieldText: "FFFFFFFF" })),
    panel: panelSpec("FFA9ADB2", "brushed", 60, 50),
    tokens: {
      "surface": "FF3B3D42",
      "surface.hover": "FF4A4D53",
      "surface.pressed": "FF2A2C30",
      "surface.checked": "FF3B3D42",
      "surface.mixed": "FFB3832E",
      "control.button": "FF3B3D42",
      "control.button.hover": "FF4B4D51",
      "control.button.pressed": "FF35373B",
      "control.field": "FF16171A",
      "control.field.hover": "FF222325",
      "control.field.active": "FF555659",
      "control.select": "FF2F3136",
      "control.select.hover": "FF404146",
      "control.select.pressed": "FF2B2D32",
      "control.track": "FF2A2C30",
      "control.track.edge": "550F1012",
      "control.fill": "FFE8EAED",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FF6E747A",
      "control.range.hot": "FF84898E",
      "control.cap": "FF16171A",
      "control.cap.hot": "FF2D2E31",
      "control.cap.edge": "992A2A2A",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FFF4F4F4",
      "control.tick": "CC1B1B1D",
      "control.tick.minor": "881B1B1D",
      "accent": "FFE8EAED",
      "accent.hot": "FF7CFF6B",
      "text.primary": "FF1B1B1D",
      "text.label": "FF1B1B1D",
      "text.muted": "FF3F4247",
      "text.focus": "FF000000",
      "text.inverse": "FF0A0A0B",
      "border": "660A0A0B",
      "border.surface": "660A0A0B",
      "border.field": "660A0A0B",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "reel",
    name: "Reel",
    description: "A seventies tape machine. Grey-green hammertone, big bakelite knobs with a numbered skirt, bat-handle toggle switches, needle meters.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 78, capMaterial: ["rubber", 60, 0], pointer: "line", pointerWidth: 3, pointerLength: 84, track: 6 }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["hammer", 50, 40] })),
    panel: panelSpec("FF5E6A5E", "hammer", 80, 40),
    tokens: {
      "surface": "FF3A4038",
      "surface.hover": "FF454C43",
      "surface.pressed": "FF2B302A",
      "surface.checked": "FF3A4038",
      "surface.mixed": "FFB3832E",
      "control.button": "FF3A4038",
      "control.button.hover": "FF4A4F48",
      "control.button.pressed": "FF343A32",
      "control.field": "FF1E2420",
      "control.field.hover": "FF292F2B",
      "control.field.active": "FF5B5D54",
      "control.select": "FF2E3530",
      "control.select.hover": "FF3F4541",
      "control.select.pressed": "FF2A312C",
      "control.track": "FF2E3530",
      "control.track.edge": "55141814",
      "control.fill": "FFE9E2CC",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FFA6AE9E",
      "control.range.hot": "FFB3BAAD",
      "control.cap": "FF1E1B18",
      "control.cap.hot": "FF34322F",
      "control.cap.edge": "998A8F94",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF8FB07A",
      "control.marker": "FFF3EEDD",
      "control.tick": "CC1E1B18",
      "control.tick.minor": "881E1B18",
      "accent": "FFE9E2CC",
      "accent.hot": "FFF2C462",
      "text.primary": "FFF3EEDD",
      "text.label": "FFF3EEDD",
      "text.muted": "FFC9CEC2",
      "text.focus": "FFFFF3D6",
      "text.inverse": "FF1E1B18",
      "border": "66141814",
      "border.surface": "66141814",
      "border.field": "66141814",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "valve",
    name: "Valve",
    description: "A valve radio. Bakelite brown with a gold ring on every knob, a lacquered wood surround, cream dial text and a nixie-tube readout glowing orange.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, capEdgeWidth: 2.5, capMaterial: ["rubber", 40, 20], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5 }), buttonFamily({ radius: 8, border: 1, buttonMaterial: ["glass", 40, 80] })),
    panel: panelSpec("FF6B4A2E", "brushed", 50, 30, 60),
    tokens: {
      "surface": "FF4A3A30",
      "surface.hover": "FF5A4738",
      "surface.pressed": "FF33271F",
      "surface.checked": "FFB08D3C",
      "surface.mixed": "FFB3832E",
      "control.button": "FF4A3A30",
      "control.button.hover": "FF584A41",
      "control.button.pressed": "FF43342B",
      "control.field": "FF1A1410",
      "control.field.hover": "FF25201C",
      "control.field.active": "FF564930",
      "control.select": "FF33271F",
      "control.select.hover": "FF433831",
      "control.select.pressed": "FF2F241D",
      "control.track": "FF1A1410",
      "control.track.edge": "550D0906",
      "control.fill": "FFE3C67A",
      "control.fill.hot": "FFFFE7A3",
      "control.range": "FFB08D3C",
      "control.range.hot": "FFBC9E59",
      "control.cap": "FF3A2A22",
      "control.cap.hot": "FF4E3F38",
      "control.cap.edge": "99B08D3C",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF8FB07A",
      "control.marker": "FFF6E7C8",
      "control.tick": "CCF6E7C8",
      "control.tick.minor": "88F6E7C8",
      "accent": "FFE3C67A",
      "accent.hot": "FFFFB020",
      "text.primary": "FFF6E7C8",
      "text.label": "FFF6E7C8",
      "text.muted": "FFCDB99A",
      "text.focus": "FFFFF3D6",
      "text.inverse": "FF22170F",
      "border": "6615100D",
      "border.surface": "6615100D",
      "border.field": "6615100D",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "anodised",
    name: "Anodised",
    description: "Photographed, not drawn. Machined aluminium knobs with real knurling and a domed cap, engraved legends, slot faders with a 3D cap, buttons that sit proud of the panel.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capMaterial: ["brushed", 80, 90], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5 }), buttonFamily({ radius: 4, border: 1, buttonMaterial: ["blast", 80, 60], fieldText: "FFFFFFFF" })),
    panel: panelSpec("FF9DA3AA", "blast", 90, 40),
    tokens: {
      "surface": "FFB8BDC3",
      "surface.hover": "FFCDD2D7",
      "surface.pressed": "FF8E949B",
      "surface.checked": "FFB8BDC3",
      "surface.mixed": "FFB3832E",
      "control.button": "FFB8BDC3",
      "control.button.hover": "FFBEC2C8",
      "control.button.pressed": "FFA6AAB0",
      "control.field": "FF1B1D20",
      "control.field.hover": "FF26282B",
      "control.field.active": "FF582F1A",
      "control.select": "FF2B2E32",
      "control.select.hover": "FF3C3F42",
      "control.select.pressed": "FF282A2E",
      "control.track": "FF2B2E32",
      "control.track.edge": "55141618",
      "control.fill": "FFE8590C",
      "control.fill.hot": "FFFF7A1A",
      "control.range": "FF8A5A3A",
      "control.range.hot": "FF9C7358",
      "control.cap": "FFC9CED3",
      "control.cap.hot": "FFCED3D7",
      "control.cap.edge": "992A2D31",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FF1B1D20",
      "control.tick": "CC1B1D20",
      "control.tick.minor": "881B1D20",
      "accent": "FFE8590C",
      "accent.hot": "FF7CFF6B",
      "text.primary": "FF1B1D20",
      "text.label": "FF1B1D20",
      "text.muted": "FF2E3238",
      "text.focus": "FF000000",
      "text.inverse": "FF1B1D20",
      "border": "663A3F45",
      "border.surface": "663A3F45",
      "border.field": "663A3F45",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "ladder",
    name: "Ladder",
    description: "Black panel between real walnut cheeks. Big fluted Davies-style knobs with a deep shadow, cream silkscreen, bat-handle toggles in the round, a needle in a lit window.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 78, capMaterial: ["rubber", 70, 10], pointer: "line", pointerWidth: 3, pointerLength: 86, track: 6 }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["rubber", 50, 10] })),
    panel: panelSpec("FF1B1B1D", "rubber", 40, 0),
    tokens: {
      "surface": "FF2A2A2D",
      "surface.hover": "FF3A3A3E",
      "surface.pressed": "FF151517",
      "surface.checked": "FF2A2A2D",
      "surface.mixed": "FFB3832E",
      "control.button": "FF2A2A2D",
      "control.button.hover": "FF3B3B3E",
      "control.button.pressed": "FF262628",
      "control.field": "FF0A0A0B",
      "control.field.hover": "FF161617",
      "control.field.active": "FF4F4C46",
      "control.select": "FF151517",
      "control.select.hover": "FF28282A",
      "control.select.pressed": "FF131315",
      "control.track": "FF0A0A0B",
      "control.track.edge": "55000000",
      "control.fill": "FFF1E6CF",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FF8C7A5A",
      "control.range.hot": "FF9D8E73",
      "control.cap": "FF151517",
      "control.cap.hot": "FF2C2C2E",
      "control.cap.edge": "992A2A2C",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF8FB07A",
      "control.marker": "FFF1E6CF",
      "control.tick": "CCF1E6CF",
      "control.tick.minor": "88F1E6CF",
      "accent": "FFF1E6CF",
      "accent.hot": "FFFF3B30",
      "text.primary": "FFF1E6CF",
      "text.label": "FFF1E6CF",
      "text.muted": "FFC9BEA6",
      "text.focus": "FFFFFFFF",
      "text.inverse": "FF1B1B1D",
      "border": "66050506",
      "border.surface": "66050506",
      "border.field": "66050506",
      "border.mixed": "FFE0A43A",
    },
  },
  {
    id: "eurorack",
    name: "Eurorack",
    description: "A module in a case. Aluminium faceplate between the rails, chrome domed knobs with a knurled rim, 3.5 mm sockets with hex nuts, LEDs with a lens and bloom, lens-capped sliders.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 66, capMaterial: ["glass", 60, 200], pointer: "line", pointerWidth: 2.5, pointerLength: 80, track: 5 }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["blast", 60, 60], fieldText: "FFFFFFFF" })),
    panel: panelSpec("FFC4C8CC", "brushed", 60, 50),
    tokens: {
      "surface": "FFD5D9DD",
      "surface.hover": "FFE6E9EC",
      "surface.pressed": "FFA6ABB0",
      "surface.checked": "FFD5D9DD",
      "surface.mixed": "FFCC8D1A",
      "control.button": "FFD5D9DD",
      "control.button.hover": "FFD8DCE0",
      "control.button.pressed": "FFC0C3C7",
      "control.field": "FF1B1D20",
      "control.field.hover": "FF26282B",
      "control.field.active": "FF24613B",
      "control.select": "FF2B2E32",
      "control.select.hover": "FF3C3F42",
      "control.select.pressed": "FF282A2E",
      "control.track": "FF2B2E32",
      "control.track.edge": "55141618",
      "control.fill": "FF39FF7A",
      "control.fill.hot": "FFB8FFD2",
      "control.range": "FF6EA6FF",
      "control.range.hot": "FF84B3FF",
      "control.cap": "FFE2E5E8",
      "control.cap.hot": "FFE5E8EA",
      "control.cap.edge": "992A2D31",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF39FF7A",
      "control.marker": "FF1B1D20",
      "control.tick": "CC1B1D20",
      "control.tick.minor": "881B1D20",
      "accent": "FF39FF7A",
      "accent.hot": "FF39FF7A",
      "text.primary": "FF1B1D20",
      "text.label": "FF1B1D20",
      "text.muted": "FF2E3238",
      "text.focus": "FF000000",
      "text.inverse": "FF1B1D20",
      "border": "662A2D31",
      "border.surface": "662A2D31",
      "border.field": "662A2D31",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "backlit",
    name: "Backlit",
    description: "A dark instrument in a dark room. Every legend is backlit, every knob sits on an underlit ring, rubber keys bleed light at the edges, an OLED readout glows through glass.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, pointer: "line", pointerWidth: 3, pointerLength: 84, track: 6 }), buttonFamily({ radius: 6, border: 1 })),
    panel: panelSpec("FF121316"),
    tokens: {
      "surface": "FF1F2126",
      "surface.hover": "FF2A2D34",
      "surface.pressed": "FF101114",
      "surface.checked": "FF1F2126",
      "surface.mixed": "FFCC9356",
      "control.button": "FF1F2126",
      "control.button.hover": "FF313337",
      "control.button.pressed": "FF1C1E22",
      "control.field": "FF0A0B0D",
      "control.field.hover": "FF161719",
      "control.field.active": "FF1E4956",
      "control.select": "FF16181C",
      "control.select.hover": "FF292A2E",
      "control.select.pressed": "FF14161A",
      "control.track": "FF1F2126",
      "control.track.edge": "55000000",
      "control.fill": "FF4DD9FF",
      "control.fill.hot": "FFB6F0FF",
      "control.range": "FFB58CFF",
      "control.range.hot": "FFC09DFF",
      "control.cap": "FF1A1B1F",
      "control.cap.hot": "FF313235",
      "control.cap.edge": "99000000",
      "control.cap.start": "FFFFB86C",
      "control.cap.end": "FFB58CFF",
      "control.marker": "FF4DD9FF",
      "control.tick": "CC5A5F6A",
      "control.tick.minor": "885A5F6A",
      "accent": "FF4DD9FF",
      "accent.hot": "FF4DD9FF",
      "text.primary": "FFDCE9F5",
      "text.label": "FFDCE9F5",
      "text.muted": "FF8FA0B3",
      "text.focus": "FFB6F0FF",
      "text.inverse": "FF121316",
      "border": "66000000",
      "border.surface": "66000000",
      "border.field": "66000000",
      "border.mixed": "FFFFB86C",
    },
  },
  {
    id: "saddle",
    name: "Saddle & Brass",
    description: "Saddle-stitched leather over a case; a brushed-brass escutcheon plate carries the controls. Cream enamel dials in brass bezels, red jewel lamps, a mirror-scale VU.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, capEdgeWidth: 3, capMaterial: ["glass", 30, 60], pointer: "line", pointerWidth: 2, pointerLength: 84, track: 5 }), buttonFamily({ radius: 5, border: 1, buttonMaterial: ["brushed", 60, 80], fieldText: "FFFFFFFF" })),
    panel: panelSpec("FFB3873A", "brushed", 60, 70),
    tokens: {
      "surface": "FFD9B45B",
      "surface.hover": "FFE6C77A",
      "surface.pressed": "FF9A7530",
      "surface.checked": "FFB8332A",
      "surface.mixed": "FFFF2E1F",
      "control.button": "FFD9B45B",
      "control.button.hover": "FFE6C77A",
      "control.button.pressed": "FF9A7530",
      "control.field": "FF1A1208",
      "control.field.hover": "FF282017",
      "control.field.active": "FF491C12",
      "control.select": "FFD9B45B",
      "control.select.hover": "FFE6C77A",
      "control.select.pressed": "FF9A7530",
      "control.track": "FF241A12",
      "control.track.edge": "5519120D",
      "control.fill": "FFF3ECD9",
      "control.fill.hot": "FFE85A4F",
      "control.range": "FF8A6320",
      "control.range.hot": "FFA1824D",
      "control.cap": "FFF3ECD9",
      "control.cap.hot": "FFF4EEDD",
      "control.cap.edge": "FFC99A44",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FF2A211A",
      "control.tick": "CC2A211A",
      "control.tick.minor": "882A211A",
      "accent": "FFB8332A",
      "accent.hot": "FFE85A4F",
      "text.primary": "FF2A211A",
      "text.label": "FF2A211A",
      "text.muted": "FF3E2E22",
      "text.focus": "FFE85A4F",
      "text.inverse": "FF2A211A",
      "border": "66826C37",
      "border.surface": "AA6C5A2E",
      "border.field": "66826C37",
      "border.mixed": "FFFF2E1F",
    },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "A slab of black glass in a dark room. Cut-glass pucks on illuminated rings, light-guide pointers, keys that glow through frosted glass, an OLED behind the same pane.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, capMaterial: ["glass", 80, 160], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5, readoutFill: "{control.marker}" }), buttonFamily({ radius: 7, border: 1, buttonMaterial: ["glass", 50, 120] })),
    panel: panelSpec("FF0B0D11", "glass", 40, 120),
    tokens: {
      "surface": "FF161A21",
      "surface.hover": "FF1E232B",
      "surface.pressed": "FF0B0D11",
      "surface.checked": "FF5FE3FF",
      "surface.mixed": "FFC98A2A",
      "control.button": "FF161A21",
      "control.button.hover": "FF1E232B",
      "control.button.pressed": "FF0B0D11",
      "control.field": "FF03040A",
      "control.field.hover": "FF121319",
      "control.field.active": "FF1F4754",
      "control.select": "FF161A21",
      "control.select.hover": "FF1E232B",
      "control.select.pressed": "FF0B0D11",
      "control.track": "FF030406",
      "control.track.edge": "55020304",
      "control.fill": "FF5FE3FF",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FFB58CFF",
      "control.range.hot": "FFC4A3FF",
      "control.cap": "FF161A21",
      "control.cap.hot": "FF2D3137",
      "control.cap.edge": "990B0D10",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FFFFFFFF",
      "control.tick": "CC5A6270",
      "control.tick.minor": "885A6270",
      "accent": "FF5FE3FF",
      "accent.hot": "FFFFFFFF",
      "text.primary": "FFE6F0FA",
      "text.label": "FFE6F0FA",
      "text.muted": "FF7FDCF2",
      "text.focus": "FFFFFFFF",
      "text.inverse": "FF9FE9FF",
      "border": "660D1014",
      "border.surface": "AA0B0D10",
      "border.field": "660D1014",
      "border.mixed": "FFC98A2A",
    },
  },
  {
    id: "laboratory",
    name: "Laboratory",
    description: "A 1950s bench instrument. Hammertone grey-green steel with rivets and a folded top edge, bakelite knobs with fluted skirts, ceramic rockers, an engraved brass nameplate.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, capMaterial: ["rubber", 50, 30], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5 }), buttonFamily({ radius: 4, border: 1, buttonMaterial: ["glass", 30, 60] })),
    panel: panelSpec("FF5F6B5E", "hammer", 80, 40),
    tokens: {
      "surface": "FF4A5548",
      "surface.hover": "FF5A665A",
      "surface.pressed": "FF2E362D",
      "surface.checked": "FFB8332A",
      "surface.mixed": "FFC98A2A",
      "control.button": "FF4A5548",
      "control.button.hover": "FF5A665A",
      "control.button.pressed": "FF2E362D",
      "control.field": "FF1A1208",
      "control.field.hover": "FF282017",
      "control.field.active": "FF491C12",
      "control.select": "FF4A5548",
      "control.select.hover": "FF5A665A",
      "control.select.pressed": "FF2E362D",
      "control.track": "FF1C221B",
      "control.track.edge": "55141813",
      "control.fill": "FFF1EBDC",
      "control.fill.hot": "FFE85A4F",
      "control.range": "FF8A6320",
      "control.range.hot": "FFA1824D",
      "control.cap": "FF2A1E17",
      "control.cap.hot": "FF3F342E",
      "control.cap.edge": "99150F0C",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FFE3C67A",
      "control.tick": "CCF1EBDC",
      "control.tick.minor": "88F1EBDC",
      "accent": "FFB8332A",
      "accent.hot": "FFE85A4F",
      "text.primary": "FFF1EBDC",
      "text.label": "FFF1EBDC",
      "text.muted": "FFD8DDCF",
      "text.focus": "FFE85A4F",
      "text.inverse": "FFF1EBDC",
      "border": "662C332B",
      "border.surface": "AA252A24",
      "border.field": "662C332B",
      "border.mixed": "FFC98A2A",
    },
  },
  {
    id: "aerospace",
    name: "Aerospace",
    description: "A module bolted between titanium rails on a woven-carbon plate. Dull titanium knobs, guarded switches, backlit legends, an OLED. Nothing shines that is not meant to.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 70, capMaterial: ["brushed", 70, 50], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5 }), buttonFamily({ radius: 4, border: 1, buttonMaterial: ["blast", 70, 40] })),
    panel: panelSpec("FF1A1C20", "blast", 60, 20, 120),
    tokens: {
      "surface": "FF3A3F46",
      "surface.hover": "FF4A5058",
      "surface.pressed": "FF25282D",
      "surface.checked": "FF5FE3FF",
      "surface.mixed": "FFFFB020",
      "control.button": "FF3A3F46",
      "control.button.hover": "FF4A5058",
      "control.button.pressed": "FF25282D",
      "control.field": "FF03040A",
      "control.field.hover": "FF121319",
      "control.field.active": "FF1F4754",
      "control.select": "FF3A3F46",
      "control.select.hover": "FF4A5058",
      "control.select.pressed": "FF25282D",
      "control.track": "FF0A0B0D",
      "control.track.edge": "55070809",
      "control.fill": "FF5FE3FF",
      "control.fill.hot": "FFFFFFFF",
      "control.range": "FFFF7A1A",
      "control.range.hot": "FFFF9548",
      "control.cap": "FF5B6068",
      "control.cap.hot": "FF6B7077",
      "control.cap.edge": "992E3034",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF5FE3FF",
      "control.marker": "FF5FE3FF",
      "control.tick": "CC9AA0A8",
      "control.tick.minor": "889AA0A8",
      "accent": "FF5FE3FF",
      "accent.hot": "FFFFFFFF",
      "text.primary": "FFE6EBF0",
      "text.label": "FFE6EBF0",
      "text.muted": "FF7FDCF2",
      "text.focus": "FFB6F0FF",
      "text.inverse": "FFB6F0FF",
      "border": "6623262A",
      "border.surface": "AA1D2023",
      "border.field": "6623262A",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "ceramic",
    name: "Ceramic & Oak",
    description: "White glazed ceramic knobs and keys on a tiled field set into oak. Rockers in porcelain, an e-ink readout. The quiet one.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 74, capMaterial: ["glass", 40, 120], pointer: "line", pointerWidth: 2.5, pointerLength: 84, track: 5 }), buttonFamily({ radius: 5, border: 1, buttonMaterial: ["glass", 30, 100] })),
    panel: panelSpec("FFF2EFE7", "glass", 30, 60),
    tokens: {
      "surface": "FFF7F4EE",
      "surface.hover": "FFFFFFFF",
      "surface.pressed": "FFD9D4C8",
      "surface.checked": "FF2F6F9A",
      "surface.mixed": "FFD99A1E",
      "control.button": "FFF7F4EE",
      "control.button.hover": "FFFFFFFF",
      "control.button.pressed": "FFD9D4C8",
      "control.field": "FFE9E6DC",
      "control.field.hover": "FFEAE8DE",
      "control.field.active": "FFB1C2C8",
      "control.select": "FFF7F4EE",
      "control.select.hover": "FFFFFFFF",
      "control.select.pressed": "FFD9D4C8",
      "control.track": "FFB9B2A2",
      "control.track.edge": "55827D71",
      "control.fill": "FF2F6F9A",
      "control.fill.hot": "FF3E8FD0",
      "control.range": "FFD99A1E",
      "control.range.hot": "FFE1AE4B",
      "control.cap": "FFF7F4EE",
      "control.cap.hot": "FFF8F5F0",
      "control.cap.edge": "997C7A77",
      "control.cap.start": "FFD99A1E",
      "control.cap.end": "FF2E9E6E",
      "control.marker": "FF2B2A26",
      "control.tick": "CC2B2A26",
      "control.tick.minor": "882B2A26",
      "accent": "FF2F6F9A",
      "accent.hot": "FF3E8FD0",
      "text.primary": "FF2B2A26",
      "text.label": "FF2B2A26",
      "text.muted": "FF5E5A52",
      "text.focus": "FF2F6F9A",
      "text.inverse": "FF2B2A26",
      "border": "6694928F",
      "border.surface": "AA7C7A77",
      "border.field": "6694928F",
      "border.mixed": "FFD99A1E",
    },
  },
  {
    id: "field",
    name: "Field",
    description: "Olive-drab crinkle paint over a stiffened steel box. Black phenolic knobs with a white line, guarded bat switches, stencilled legends, a red LED readout. Built to be dropped.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capMaterial: ["rubber", 60, 20], pointer: "line", pointerWidth: 3, pointerLength: 84, track: 5 }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["hammer", 50, 30] })),
    panel: panelSpec("FF4F5A3C", "leather", 90, 20, 150),
    tokens: {
      "surface": "FF3A4230",
      "surface.hover": "FF4A5340",
      "surface.pressed": "FF2A3024",
      "surface.checked": "FFFF3B30",
      "surface.mixed": "FFFFB020",
      "control.button": "FF3A4230",
      "control.button.hover": "FF4A5340",
      "control.button.pressed": "FF2A3024",
      "control.field": "FF140505",
      "control.field.hover": "FF221414",
      "control.field.active": "FF5A1512",
      "control.select": "FF3A4230",
      "control.select.hover": "FF4A5340",
      "control.select.pressed": "FF2A3024",
      "control.track": "FF1F241C",
      "control.track.edge": "55161914",
      "control.fill": "FFF1EBDC",
      "control.fill.hot": "FFFF7A70",
      "control.range": "FFC9A227",
      "control.range.hot": "FFD4B552",
      "control.cap": "FF2A2A26",
      "control.cap.hot": "FF3F3F3C",
      "control.cap.edge": "99151513",
      "control.cap.start": "FFFFB020",
      "control.cap.end": "FF8FB07A",
      "control.marker": "FFF1EBDC",
      "control.tick": "CCF1EBDC",
      "control.tick.minor": "88F1EBDC",
      "accent": "FFFF3B30",
      "accent.hot": "FFFF7A70",
      "text.primary": "FFF1EBDC",
      "text.label": "FFF1EBDC",
      "text.muted": "FFD8DDCF",
      "text.focus": "FFFFB020",
      "text.inverse": "FFF1EBDC",
      "border": "6623281D",
      "border.surface": "AA1D2118",
      "border.field": "6623281D",
      "border.mixed": "FFFFB020",
    },
  },
  {
    id: "receiver",
    name: "Receiver",
    description: "A seventies stereo receiver: walnut case, brushed-aluminium faceplate, black dials with white scales in silver bezels, blue lamps, a blue fluorescent readout.",
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, capEdgeWidth: 3, capMaterial: ["glass", 30, 60], pointer: "line", pointerWidth: 2, pointerLength: 84, track: 4, readoutFill: "{control.marker}" }), buttonFamily({ radius: 3, border: 1, buttonMaterial: ["brushed", 60, 70], fieldText: "FFFFFFFF" })),
    panel: panelSpec("FFC9CED3", "brushed", 70, 60),
    tokens: {
      "surface": "FFB9BEC3",
      "surface.hover": "FFCDD2D7",
      "surface.pressed": "FF8E949B",
      "surface.checked": "FF4DA3FF",
      "surface.mixed": "FFFFB020",
      "control.button": "FFB9BEC3",
      "control.button.hover": "FFCDD2D7",
      "control.button.pressed": "FF8E949B",
      "control.field": "FF0A1020",
      "control.field.hover": "FF191E2D",
      "control.field.active": "FF1E3C63",
      "control.select": "FFB9BEC3",
      "control.select.hover": "FFCDD2D7",
      "control.select.pressed": "FF8E949B",
      "control.track": "FF1E2124",
      "control.track.edge": "55151719",
      "control.fill": "FFE8E8E8",
      "control.fill.hot": "FF8EC5FF",
      "control.range": "FF8A6320",
      "control.range.hot": "FFA1824D",
      "control.cap": "FF151517",
      "control.cap.hot": "FF2C2C2E",
      "control.cap.edge": "FFC9CED3",
      "control.cap.start": "FFE0A43A",
      "control.cap.end": "FF5CC492",
      "control.marker": "FFE8E8E8",
      "control.tick": "CC1B1D20",
      "control.tick.minor": "881B1D20",
      "accent": "FF4DA3FF",
      "accent.hot": "FF8EC5FF",
      "text.primary": "FF1B1D20",
      "text.label": "FF1B1D20",
      "text.muted": "FF3E4247",
      "text.focus": "FF1F5C88",
      "text.inverse": "FF1B1D20",
      "border": "666F7275",
      "border.surface": "AA5C5F62",
      "border.field": "666F7275",
      "border.mixed": "FFFFB020",
    },
  },
];

/** Families and panels for the colour-only built-ins whose boards showed more than colour. */
export const CATALOG_SET_EXTRAS = {
  "ember": {
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 72, pointer: "chicken", pointerWidth: 9, pointerLength: 118, track: 4, readoutFill: "{control.marker}" }), buttonFamily({ radius: 6 })),
    panel: panelSpec("FF2A2320", "rubber", 40, 0),
    tokens: { "control.marker": "FF3B2A1E" },
  },
  "ivory": {
    lamp: LAMP,
    families: mergeFamilies(knobFamily({ cap: 68, pointer: "line", pointerWidth: 3, pointerLength: 72, track: 4 }), buttonFamily({ radius: 4 })),
    panel: panelSpec("FFEFEAE0"),
    tokens: { "control.marker": "FF22201C" },
  },
};
