-- CTRL49 screen lab: the stress page. It finds the two numbers the screen's design is waiting
-- on — how much the device can draw per redraw, and how much image memory it has — by drawing
-- as much as the encoders ask for, as often as they ask, until the screen stutters or the
-- keyboard's watchdog restores its own screen.
--
-- The host (Ctrl49ScreenLab.cpp, from Ctrl49ScreenLab.h) sends, once per redraw:
--   set_load  [rects/16][sprites/8][texts][fullScreens][memoryBlocks][fps][frameHi][frameLo]
--
-- What to watch: the orange bar under the header moves 8 px per redraw and the counter counts
-- them. Smooth and counting = the device keeps up. Jerky, or the counter jumping = it does not.
-- The stock screen coming back = the watchdog gave up; the console has the load that did it.
-- The swatches along the bottom are crops of each decoded 1 MB block: one missing is a decode
-- that failed, which is the memory ceiling.
--
-- Standard libraries are not assumed: no math.*, only what the proven pages already use.

-- BEGIN SPRITES (generated by make_lab_assets.py; do not edit by hand)
local SPR = { pad = { 0, 0, 100, 78 }, padrim = { 101, 0, 100, 78 }, cap = { 202, 0, 26, 14 }, caprim = { 229, 0, 26, 14 }, dot = { 256, 0, 8, 8 }, btn = { 265, 0, 44, 20 }, btnrim = { 310, 0, 44, 20 } }
-- END SPRITES

local FLAT, FLAT_PNG = 0x0221, 0x0220
local BG, BG_PNG     = 0x0231, 0x0230
local BLOCK_PNG      = 0x0250          -- 0x0250..0x0257, one per 1 MB block
local BLOCK          = 0x0260          -- decoded as 0x0260..0x0267

local BLACK, WHITE, GREY, ORANGE = 0xFF07090D, 0xFFFFFFFF, 0xFFAAB2BF, 0xFFFF9408
local COLOURS = { 0xFF2F6FDF, 0xFF3FBF7F, 0xFFDF5F3F, 0xFFBF3FBF, 0xFFDFBF3F, 0xFF3FBFDF }

local work = { rects = 0, sprites = 0, texts = 0, full = 0, mem = 0, fps = 0, frame = 0 }
local decoded = 0
local HUD, HUD2, BIGNUM, TXT
local initialized = false

local function textbox (font, size, hor, colour)
    local t = text_data.new()
    text_data.set(t, { text = "", color = colour, font = font, font_size = size, just_ver = 1,
                       just_hor = hor, bk_color = 0x00000000, border_width_top = 0,
                       border_width_bottom = 0, border_width_left = 0, border_width_right = 0 })
    return t
end

function init (args)
    if initialized then return end
    HUD = textbox(10, 13, 0, WHITE)
    HUD2 = textbox(9, 11, 0, GREY)
    BIGNUM = textbox(10, 20, 2, WHITE)
    TXT = textbox(9, 10, 0, GREY)
    decode_image(14, FLAT_PNG, 18, FLAT, WHITE)
    decode_image(14, BG_PNG, 18, BG, WHITE)
    initialized = true
end

function set_mode (args) end

function set_load (args)
    work.rects   = get_byte(args, 0) * 16
    work.sprites = get_byte(args, 1) * 8
    work.texts   = get_byte(args, 2)
    work.full    = get_byte(args, 3)
    work.mem     = get_byte(args, 4)
    work.fps     = get_byte(args, 5)
    work.frame   = get_byte(args, 6) * 256 + get_byte(args, 7)
end

function draw (args)
    if not initialized then init("") end

    -- Memory: decode one more block per redraw until the asked-for count is reached. There is
    -- no way to free one, so the count only ever goes up.
    if decoded < work.mem and decoded < 8 then
        decode_image(14, BLOCK_PNG + decoded, 18, BLOCK + decoded, WHITE)
        decoded = decoded + 1
    end

    draw_rect(0, 0, 480, 272, BLACK)

    -- Full-screen image blits: the most pixels one call can move.
    for i = 1, work.full do draw_image(18, BG, 0, 0, 0, 0, 480, 272, WHITE) end

    -- Rectangles and sprites, scattered by fixed strides so every redraw is the same work.
    for i = 1, work.rects do
        draw_rect((i * 73) % 440 + 20, (i * 151) % 176 + 44, 16, 10, COLOURS[i % 6 + 1])
    end
    local cap = SPR.cap
    for i = 1, work.sprites do
        draw_image(18, FLAT, (i * 97) % 440 + 14, (i * 59) % 170 + 46,
                   cap[1], cap[2], cap[3], cap[4], COLOURS[(i + 3) % 6 + 1])
    end
    for i = 1, work.texts do
        text_data.set(TXT, { text = tostring(i) })
        draw_text(TXT, (i * 41) % 420 + 20, (i * 67) % 160 + 50, 40, 12)
    end

    -- The memory swatches: a crop of every block decoded so far, from a different band each.
    for b = 0, decoded - 1 do
        draw_image(18, BLOCK + b, 16 + b * 30, 236, 0, b * 128, 26, 26, WHITE)
    end

    -- The HUD last, so it is always on top and always readable.
    draw_rect(0, 0, 480, 40, BLACK)
    draw_rect(0, 0, 480, 3, ORANGE)
    text_data.set(HUD, { text = "RECT " .. work.rects .. "  SPRITE " .. work.sprites
                               .. "  TEXT " .. work.texts .. "  FULL " .. work.full })
    draw_text(HUD, 10, 5, 400, 18)
    text_data.set(HUD2, { text = "MEMORY " .. decoded .. " MB extra  -  " .. work.fps
                                .. " redraws/s  -  "
                                .. (work.rects + work.sprites + work.texts + work.full)
                                .. " calls per redraw" })
    draw_text(HUD2, 10, 22, 460, 14)
    text_data.set(BIGNUM, { text = tostring(work.frame) })
    draw_text(BIGNUM, 380, 4, 90, 22)
    draw_rect(0, 40, 480, 3, 0xFF1C222B)
    draw_rect((work.frame * 8) % 440, 40, 40, 3, ORANGE)
end
