-- CTRL49 screen lab: the showcase. Six pages of how far pre-rendered PNGs take the screen past
-- flat rectangles — flat faders and RGB pads with tinted white shapes, then a step sequencer,
-- an envelope and a pair of analog VU meters in full colour, and a page of animation.
--
-- The firmware draws filled rectangles, text boxes, and sub-rectangles of uploaded PNGs with a
-- tint. Nothing else: no lines, arcs, pixels, scaling or rotation. So every gradient, gloss,
-- glow, shadow and rotated needle is baked into the PNGs (make_lab_assets.py), and this page
-- only crops and places them. The host does the maths (Ctrl49ScreenLab.h) and sends
--   set_frame     [page][frameLo][e1..e8][lastEncoder][playhead][vuL][vuR][padsLit][frameHi]
--   set_envelope  [110 column heights][attackCol][decayEndCol][releaseStartCol][sustain] + 4 texts
-- This page keeps the demo content itself, so the lab needs no synth.
--
-- Standard libraries are not assumed: no math.*, only what the proven pages already use.

-- BEGIN SPRITES (generated by make_lab_assets.py; do not edit by hand)
local SPR = { pad = { 0, 0, 100, 78 }, padrim = { 101, 0, 100, 78 }, cap = { 202, 0, 26, 14 }, caprim = { 229, 0, 26, 14 }, dot = { 256, 0, 8, 8 }, btn = { 265, 0, 44, 20 }, btnrim = { 310, 0, 44, 20 } }
local R = { step_off = { 0, 0, 24, 30 }, step_on = { 25, 0, 24, 30 }, step_acc = { 50, 0, 24, 30 }, playhead = { 75, 0, 30, 36 }, vel = { 106, 0, 14, 100 }, envfill = { 121, 0, 4, 140 }, glow = { 126, 0, 10, 10 }, handle = { 137, 0, 16, 16 } }
-- END SPRITES

-- PNG object ids (uploaded by the host) and the decoded images this page makes of them.
local FLAT, FLAT_PNG     = 0x0221, 0x0220
local BG, BG_PNG         = 0x0231, 0x0230
local RICH, RICH_PNG     = 0x0233, 0x0232
local VUFACE, VUFACE_PNG = 0x0235, 0x0234
local NEEDLE, NEEDLE_PNG = 0x0237, 0x0236
local LOGO, LOGO_PNG     = 0x0239, 0x0238     -- 220x40 x 16 frames
local SPIN, SPIN_PNG     = 0x023B, 0x023A     -- 32x32 x 16 frames, white

local BLACK, WHITE, GREY = 0xFF07090D, 0xFFFFFFFF, 0xFFAAB2BF
local DIM, DARK, ORANGE  = 0xFF5A6B82, 0xFF3A4352, 0xFFFF9408
local TRACK, LINE, GRID  = 0xFF1C222B, 0xFF222933, 0xFF1E2A36
local CYAN_TEXT          = 0xFF9FE8FF

local function floor (x) return x - x % 1 end
-- A whole number as text. Lua 5.3+ keeps floor()'s result a float ("78.0"); 5.2, which the
-- device runs, prints "78". This prints "78" on both, so the preview matches the keyboard.
local function whole (x)
    local s = tostring(floor(x))
    if s:sub(-2) == ".0" then s = s:sub(1, -3) end
    return s
end

-- --- state, as the host last sent it ---------------------------------------------------------

local page, frame, lastEncoder, playhead, vuL, vuR, padsLit = 0, 0, 0, 0, 0, 0, 0
local enc = { 64, 64, 64, 64, 64, 64, 64, 64 }
local env = { cols = {}, a = 0, d = 0, r = 0, sus = 0, texts = { "", "", "", "" } }

-- The demo content.
local FADER_NAMES = { "Cutoff", "Reso", "Attack", "Decay", "Sustain", "Release", "Drive", "Chorus" }
local param = { 88, 40, 20, 64, 96, 50, 30, 70 }     -- where each parameter is
local picked = { false, false, false, false, false, false, false, false }
local BUTTONS = { { "ARP", 2 }, { "HOLD", 1 }, { "MONO", 1 }, { "", 0 },
                  { "FX", 2 }, { "", 0 }, { "", 0 }, { "MUTE", 1 } }
-- name, lit colour, dim colour, layers, active layer. The host would compute the dim colour;
-- here it is written out.
local PADS = {
    { "Kick",   0xFFFFA500, 0xFF613F00, 1, 1 }, { "Delay",  0xFF00C8FF, 0xFF004C61, 3, 2 },
    { "Snare",  0xFFFF3080, 0xFF611230, 1, 1 }, { "Riser",  0xFFFFA500, 0xFF613F00, 4, 1 },
    { "Hold",   0xFFFFA500, 0xFF613F00, 2, 1 }, { "Chorus", 0xFF7FD0FF, 0xFF304F61, 1, 1 },
    { "",       0,          0,          1, 1 }, { "Filter", 0xFFE040FF, 0xFF551861, 2, 2 },
}
local LAYER_LIT = { 0xFFFFA500, 0xFF00C8FF, 0xFFE040FF, 0xFF40FF60 }
local LAYER_DIM = { 0xFF593A00, 0xFF004659, 0xFF4E1659, 0xFF165921 }
local STEPS = { 0, 0, 0, 0, 0, 0, 0, 0, 127, 0, 60, 0, 0, 90, 50, 110 }  -- 9-16; 1-8 are E1-E8
local POW2 = { 1, 2, 4, 8, 16, 32, 64, 128 }

-- --- drawing helpers ------------------------------------------------------------------------

local function flat (name, x, y, tint)
    local s = SPR[name]
    draw_image(18, FLAT, x, y, s[1], s[2], s[3], s[4], tint)
end

-- A full-colour piece; srcH crops from the BOTTOM, so a bar grows up from its base.
local function rich (name, x, y, srcH)
    local s = R[name]
    local h = srcH or s[4]
    draw_image(18, RICH, x, y + (s[4] - h), s[1], s[2] + (s[4] - h), s[3], h, WHITE)
end

local function textbox (font, size, hor)
    local t = text_data.new()
    text_data.set(t, { text = "", color = WHITE, font = font, font_size = size, just_ver = 1,
                       just_hor = hor, bk_color = 0x00000000, border_width_top = 0,
                       border_width_bottom = 0, border_width_left = 0, border_width_right = 0 })
    return t
end

local TITLE, RIGHT, NAME, SMALL, BTN, LEG, BIG, CORNER, FOOT
local initialized = false

local function say (t, s, c, x, y, w, h)
    text_data.set(t, { text = s, color = c })
    draw_text(t, x, y, w, h)
end

function init (args)
    if initialized then return end
    TITLE = textbox(10, 15, 0); RIGHT = textbox(9, 12, 2); NAME = textbox(9, 11, 1)
    SMALL = textbox(9, 10, 1);  BTN = textbox(9, 10, 1);   LEG = textbox(9, 9, 1)
    BIG = textbox(10, 15, 1);   CORNER = textbox(9, 10, 0); FOOT = textbox(9, 11, 1)
    decode_image(14, FLAT_PNG, 18, FLAT, WHITE)
    decode_image(14, BG_PNG, 18, BG, WHITE)
    decode_image(14, RICH_PNG, 18, RICH, WHITE)
    decode_image(14, VUFACE_PNG, 18, VUFACE, WHITE)
    decode_image(14, NEEDLE_PNG, 18, NEEDLE, WHITE)
    decode_image(14, LOGO_PNG, 18, LOGO, WHITE)
    decode_image(14, SPIN_PNG, 18, SPIN, WHITE)
    initialized = true
end

-- The loading dwell draws once with mode 0; the lab has nothing to show before its first frame.
function set_mode (args) end

-- --- what the host sends ------------------------------------------------------------------------

function set_frame (args)
    page = get_byte(args, 0)
    frame = get_byte(args, 1)
    for i = 1, 8 do enc[i] = get_byte(args, 1 + i) end
    lastEncoder = get_byte(args, 10)
    playhead = get_byte(args, 11)
    vuL = get_byte(args, 12)
    vuR = get_byte(args, 13)
    padsLit = get_byte(args, 14)
    frame = frame + get_byte(args, 15) * 256
end

function set_envelope (args)
    for c = 1, 110 do env.cols[c] = get_byte(args, c - 1) end
    env.a = get_byte(args, 110)
    env.d = get_byte(args, 111)
    env.r = get_byte(args, 112)
    env.sus = get_byte(args, 113)
    local i = 114
    for t = 1, 4 do
        local n = get_byte(args, i); i = i + 1
        env.texts[t] = args:sub(i + 1, i + n); i = i + n
    end
end

-- --- the pages ------------------------------------------------------------------------------

local function flat_chrome (left, right)
    draw_rect(0, 0, 480, 272, BLACK)
    draw_rect(0, 0, 480, 3, ORANGE)
    say(TITLE, left, WHITE, 10, 5, 300, 20)
    say(RIGHT, right, GREY, 250, 5, 220, 20)
end

local function rich_chrome (left, right)
    draw_image(18, BG, 0, 0, 0, 0, 480, 272, WHITE)
    draw_rect(0, 0, 480, 3, ORANGE)
    say(TITLE, left, WHITE, 14, 8, 300, 22)
    say(RIGHT, right, GREY, 250, 8, 216, 22)
end

local function footer (text)
    draw_rect(0, 252, 480, 1, LINE)
    say(FOOT, text .. "     PAGE < > " .. (page + 1) .. "/6", DIM, 0, 255, 480, 15)
end

-- Faders, flat: rectangles and a tinted cap. The encoders stand in for the physical faders,
-- and the pickup is real: a fader moves its parameter only once it has reached it, and until
-- then an outline shows where the fader is while the cap stays where the value is.
local function draw_faders ()
    flat_chrome("FADERS  Stage Keys", "LAYER 1/2")
    flat("dot", 382, 11, ORANGE)
    flat("dot", 393, 11, DARK)
    local top, height = 48, 136
    for i = 0, 8 do
        local x = 6 + i * 52
        local cx = x + 26
        local name, value, physical
        if i == 0 then
            name, value, physical = "Level", 100, -1
        else
            name = FADER_NAMES[i]
            physical = enc[i]
            if not picked[i] and physical - param[i] <= 3 and param[i] - physical <= 3 then picked[i] = true end
            if picked[i] then param[i] = physical end
            value = param[i]
        end
        say(NAME, name, WHITE, x, 30, 52, 14)
        for t = 0, 4 do draw_rect(cx - 13, top + floor(t * height / 4), 6, 1, DARK) end
        draw_rect(cx - 2, top, 4, height, TRACK)
        local h = floor(value * height / 127)
        draw_rect(cx - 2, top + height - h, 4, h, ORANGE)
        if physical >= 0 and not picked[i] then
            local p = floor(physical * height / 127)
            flat("caprim", cx - 13, top + height - p - 7, ORANGE)
        end
        flat("cap", cx - 13, top + height - h - 7, WHITE)
        say(NAME, whole(value * 100 / 127) .. "%", GREY, x, 188, 52, 14)
        if i == 0 then
            say(LEG, "MASTER", DIM, x, 232, 52, 12)
        else
            local b = BUTTONS[i]
            if b[2] == 2 then
                flat("btn", cx - 22, 208, ORANGE); say(BTN, b[1], BLACK, cx - 22, 208, 44, 20)
            elseif b[2] == 1 then
                flat("btn", cx - 22, 208, DARK); say(BTN, b[1], WHITE, cx - 22, 208, 44, 20)
            else
                flat("btnrim", cx - 22, 208, DARK)
            end
            say(LEG, "B" .. i, DIM, cx - 22, 232, 44, 12)
        end
    end
    footer("E1-E8 = FADERS  outline = fader until it picks up")
end

-- Pads, flat: one white rounded square tinted in each pad's own colour; strike a pad to light it.
local function draw_pads ()
    flat_chrome("PADS  Stage Keys", "PAD BANK A")
    for i = 1, 8 do
        local p = PADS[i]
        local x = 22 + ((i - 1) % 4) * 112
        local y = 34
        if i > 4 then y = 124 end
        local lit = floor(padsLit / POW2[i]) % 2 == 1
        if p[2] == 0 then
            flat("padrim", x, y, DARK)
            say(BIG, "empty", DARK, x, y + 22, 100, 22)
        else
            flat("pad", x, y, lit and p[2] or p[3])
            say(CORNER, tostring(i), lit and BLACK or DIM, x + 8, y + 5, 20, 12)
            say(BIG, p[1], lit and BLACK or WHITE, x, y + 22, 100, 22)
            if p[4] > 1 then
                say(CORNER, "L" .. p[5], lit and BLACK or GREY, x + 76, y + 5, 20, 12)
                local left = x + 50 - floor((p[4] * 11 - 3) / 2)
                for l = 1, p[4] do
                    local c = LAYER_DIM[l]
                    if lit then c = (l == p[5]) and BLACK or p[3]
                    elseif l == p[5] then c = LAYER_LIT[l] end
                    flat("dot", left + (l - 1) * 11, y + 58, c)
                end
            end
        end
    end
    footer("STRIKE A PAD TO LIGHT IT")
end

-- A step sequencer in full colour: glossy baked step buttons, velocity bars cropped from one
-- gradient sprite, a playhead halo. Steps 1-8 follow E1-E8 (0 = off).
local function draw_sequencer ()
    rich_chrome("STEP SEQUENCER  Bassline", "120 BPM  -  SWING 56%  -  1/16")
    for i = 1, 16 do
        local vel = STEPS[i]
        if i <= 8 then vel = enc[i] end
        local on = vel > 0
        local x = 16 + (i - 1) * 28
        draw_rect(x + 4, 44, 16, 104, 0xFF0B0E13)
        if on then rich("vel", x + 5, 46, floor(vel * 100 / 127)) end
        local piece = "step_off"
        if on then piece = (vel >= 120) and "step_acc" or "step_on" end
        rich(piece, x, 158)
        if i == playhead + 1 then rich("playhead", x - 3, 155) end
        say(SMALL, tostring(i), (i == playhead + 1) and WHITE or DIM, x, 192, 24, 12)
        if (i - 1) % 4 == 0 then draw_rect(x, 208, 108, 1, 0xFF2A323D) end
    end
    footer("E1-E8 = VELOCITY OF STEPS 1-8")
end

-- An envelope: a gradient area of 4 px columns cropped from one sprite, a glowing curve of dots
-- placed along its length (more where it is steep), handles on the breakpoints.
local function draw_envelope ()
    rich_chrome("ENVELOPE  Amp", "Stage Keys")
    local x0, y0, w, h = 20, 40, 440, 140
    draw_rect(x0, y0, w, h, 0xFF091017)
    for i = 1, 3 do draw_rect(x0, y0 + floor(i * h / 4), w, 1, GRID) end
    for i = 1, 7 do draw_rect(x0 + floor(i * w / 8), y0, 1, h, GRID) end
    local cols = env.cols
    for c = 1, #cols do
        if cols[c] > 0 then rich("envfill", x0 + (c - 1) * 4, y0 + h - 140, cols[c]) end
    end
    for c = 1, #cols - 1 do
        local y1, y2 = cols[c], cols[c + 1]
        local dy = y2 - y1
        if dy < 0 then dy = -dy end
        local n = 1 + floor(dy / 3)
        for k = 0, n - 1 do
            local x = (c - 1) * 4 + floor(4 * k / n)
            local y = y1 + floor((y2 - y1) * k / n)
            rich("glow", x0 + x - 5, y0 + h - y - 5)
        end
    end
    if #cols > 0 then
        local marks = { { env.a, cols[env.a + 1] }, { env.d, env.sus }, { env.r, env.sus }, { 109, cols[110] } }
        for i = 1, 4 do rich("handle", x0 + marks[i][1] * 4 - 8, y0 + h - marks[i][2] - 8) end
    end
    local labels = { "ATTACK", "DECAY", "SUSTAIN", "RELEASE" }
    for i = 1, 4 do
        local x = 20 + (i - 1) * 112
        local active = (lastEncoder == i - 1)
        say(BIG, env.texts[i], active and ORANGE or WHITE, x, 190, 104, 22)
        say(SMALL, labels[i], active and ORANGE or DIM, x, 212, 104, 14)
    end
    footer("E1-E4 = ATTACK DECAY SUSTAIN RELEASE")
end

-- Analog meters: a baked face and a 48-frame needle filmstrip; the host sends frame numbers.
local function draw_meters ()
    rich_chrome("OUTPUT  Master", "")
    for m = 1, 2 do
        local x = 30 + (m - 1) * 220
        draw_image(18, VUFACE, x, 60, 0, 0, 200, 110, WHITE)
        draw_image(18, NEEDLE, x, 60, 0, ((m == 1) and vuL or vuR) * 110, 200, 110, WHITE)
        say(SMALL, (m == 1) and "LEFT" or "RIGHT", GREY, x, 176, 200, 14)
    end
    footer("E1 = LEVEL  (demo signal)")
end

-- Animation. The device keeps no time, so every frame here is a redraw the host asked for, and
-- the frame counter it sends is the only clock: everything below is a function of it. Four
-- kinds, all from calls the page already uses —
--   flipbook  a frame of a filmstrip (the logo's sheen, the spinner): what a GIF becomes
--   movement  x/y from the counter, with easing (the cards)
--   masking   text scrolled through a strip whose ends are painted over it (the marquee)
--   tint      a colour from the counter (the breathing buttons), which costs no memory at all
local PRESETS = { "Warm Analog Pad", "Glass Bells", "Moog Bass 1974", "Choir of Machines", "Tape Strings" }
local MARQUEE = "NOW PLAYING  -  Warm Analog Pad  -  slow filter sweep, chorus, long release  -  HoSTage  -  "
local BREATHE = { { 255, 148, 8 }, { 0, 200, 255 }, { 224, 64, 255 }, { 64, 255, 96 } }

local function rgb (r, g, b) return 0xFF000000 + floor(r) * 65536 + floor(g) * 256 + floor(b) end

local function draw_animation ()
    local fps = 5 + floor(enc[1] * 25 / 127)
    rich_chrome("ANIMATION", whole(fps) .. " redraws/s  -  E1")

    -- Flipbooks: the logo's sheen sweeps once every 16 frames, then rests for 16.
    local sweep = frame % 32
    if sweep > 15 then sweep = 15 end
    draw_image(18, LOGO, 130, 36, 0, sweep * 40, 220, 40, WHITE)
    draw_image(18, SPIN, 430, 40, 0, (frame % 16) * 32, 32, 32, ORANGE)

    -- A marquee: the text slides left through a strip; its two ends are painted over it after,
    -- so it appears to scroll inside the strip whether or not the device clips text.
    local strip = 0xFF0A0D12
    draw_rect(0, 88, 480, 30, strip)
    local width = #MARQUEE * 7
    local x = 20 - (frame * 3) % width
    say(TITLE, MARQUEE, CYAN_TEXT, x, 91, width, 24)
    say(TITLE, MARQUEE, CYAN_TEXT, x + width, 91, width, 24)
    draw_image(18, BG, 0, 88, 0, 88, 20, 30, WHITE)       -- the ends: the background, put back
    draw_image(18, BG, 460, 88, 460, 88, 20, 30, WHITE)
    draw_rect(20, 88, 440, 1, LINE)
    draw_rect(20, 117, 440, 1, LINE)

    -- Cards: each preset slides in from the right, holds, and slides out to the left, eased —
    -- in fast and settling (ease-out), out slow then quick (ease-in). 60 frames per card.
    local t = frame % 60
    local card = PRESETS[floor(frame / 60) % #PRESETS + 1]
    local cx
    if t < 14 then
        local u = 1 - t / 14
        cx = 140 + floor(340 * u * u * u)
    elseif t < 46 then
        cx = 140
    else
        local u = (t - 46) / 14
        cx = 140 - floor(340 * u * u * u)
    end
    if cx < 480 and cx > -200 then
        draw_rect(cx, 128, 200, 58, 0xFF141A22)
        draw_rect(cx, 128, 4, 58, ORANGE)
        say(SMALL, "PRESET " .. whole(floor(frame / 60) % #PRESETS + 1) .. " / " .. #PRESETS, DIM, cx + 10, 132, 180, 14)
        say(BIG, card, WHITE, cx + 10, 150, 180, 26)
    end
    -- The screen's edges are put back over the card too, so it slides out of view rather than
    -- off the glass, whatever the device does with a rectangle that runs past the edge.
    draw_image(18, BG, 0, 128, 0, 128, 20, 58, WHITE)
    draw_image(18, BG, 460, 128, 460, 128, 20, 58, WHITE)

    -- Breathing: eight buttons in four colours, each on its own phase of a 40-frame breath.
    for i = 1, 8 do
        local phase = (frame + i * 5) % 40
        local level = phase
        if level > 20 then level = 40 - level end
        level = 0.25 + 0.75 * level / 20
        local c = BREATHE[(i - 1) % 4 + 1]
        flat("btn", 22 + (i - 1) * 56, 204, rgb(c[1] * level, c[2] * level, c[3] * level))
        say(BTN, "PAD " .. i, BLACK, 22 + (i - 1) * 56, 204, 44, 20)
    end
    footer("FLIPBOOK - MOVEMENT - MASKING - TINT")
end

function draw (args)
    if not initialized then init("") end
    if page == 0 then draw_faders()
    elseif page == 1 then draw_pads()
    elseif page == 2 then draw_sequencer()
    elseif page == 3 then draw_envelope()
    elseif page == 4 then draw_meters()
    else draw_animation() end
end
