#!/usr/bin/env python3
"""Assets for the CTRL49 screen lab (tools/ctrl49/screen-lab).

    python make_lab_assets.py      # writes the PNGs beside this file, updates the Lua sprite tables

Everything a flat design would draw live — gradients, glow, gloss, shadows, rotation — is baked
here once. The device only crops, places and tints. Needs Pillow.

Writes:
  surface_atlas.png  white-on-transparent shapes the device tints (pads, fader caps, buttons, dots)
  rich_atlas.png     full-colour pieces (glossy steps, playhead, velocity bar, envelope fill, glow)
  lab_bg.png         a 480x272 panel background
  vu_face.png        an analog VU face
  vu_needle.png      the needle as a 48-frame filmstrip (rotation is the one thing that must be baked)
  stress_block.png   a 256x1024 block that decodes to 1 MB, for the stress page's memory test
  logo_strip.png     the HoSTage logo as a 16-frame flipbook, a sheen sweeping across it
  spinner_strip.png  a white 16-frame loading spinner the device tints

Any GIF becomes a flipbook the same way — the device has no GIF, but a GIF is only frames:

    python make_lab_assets.py --gif in.gif out_strip.png [--width 120]

and rewrites the sprite tables between the BEGIN/END SPRITES markers in the Lua pages, so the
coordinates the pages crop by can never drift from the PNGs they crop.
"""
import math
import os
import re

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
S = 4          # supersampling: every shape is drawn at 4x and downsampled, so edges anti-alias

VU_W, VU_H, VU_FRAMES = 200, 110, 48    # Ctrl49ScreenLab.h: kVuFrames


def path(name):
    return os.path.join(HERE, name)


def canvas(w, h):
    return Image.new('RGBA', (w * S, h * S), (0, 0, 0, 0))


def down(im):
    return im.resize((im.width // S, im.height // S), Image.LANCZOS)


def shape(w, h, draw):
    im = Image.new('RGBA', (w * S, h * S), (255, 255, 255, 0))
    draw(ImageDraw.Draw(im), w * S, h * S)
    return im.resize((w, h), Image.LANCZOS)


def vgrad(w, h, top, bottom):
    im = Image.new('RGBA', (w, h))
    px = im.load()
    for y in range(h):
        t = y / max(1, h - 1)
        c = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(4))
        for x in range(w):
            px[x, y] = c
    return im


def pack(sprites, filename):
    """Packs sprites left to right into one PNG; returns {name: (x, y, w, h)}."""
    width = sum(im.width for im in sprites.values()) + len(sprites)
    height = max(im.height for im in sprites.values())
    atlas = Image.new('RGBA', (width, height), (255, 255, 255, 0))
    rects, x = {}, 0
    for name, im in sprites.items():
        atlas.paste(im, (x, 0))
        rects[name] = (x, 0, im.width, im.height)
        x += im.width + 1
    atlas.save(path(filename), optimize=True)
    return rects


def lua_table(var, rects):
    body = ', '.join(f'{n} = {{ {r[0]}, {r[1]}, {r[2]}, {r[3]} }}' for n, r in rects.items())
    return f'local {var} = {{ {body} }}'


def write_tables(lua_file, tables):
    text = open(path(lua_file)).read()
    block = ('-- BEGIN SPRITES (generated by make_lab_assets.py; do not edit by hand)\n'
             + '\n'.join(tables) + '\n-- END SPRITES')
    text, n = re.subn(r'-- BEGIN SPRITES.*?-- END SPRITES', lambda _: block, text, flags=re.S)
    assert n == 1, lua_file + ' has no sprite markers'
    open(path(lua_file), 'w').write(text)


# --- white shapes the device tints ------------------------------------------------------------

def flat_sprites():
    white = (255, 255, 255, 255)
    s = {}
    s['pad'] = shape(100, 78, lambda d, W, H: d.rounded_rectangle((0, 0, W - 1, H - 1), radius=10 * S, fill=white))
    s['padrim'] = shape(100, 78, lambda d, W, H: d.rounded_rectangle(
        (S, S, W - 1 - S, H - 1 - S), radius=10 * S, outline=white, width=2 * S))

    def cap(d, W, H):
        d.rounded_rectangle((0, 0, W - 1, H - 1), radius=3 * S, fill=white)
        d.rectangle((3 * S, H // 2 - S // 2, W - 3 * S, H // 2 + S // 2), fill=(255, 255, 255, 70))
    s['cap'] = shape(26, 14, cap)
    s['caprim'] = shape(26, 14, lambda d, W, H: d.rounded_rectangle(
        (S // 2, S // 2, W - 1 - S // 2, H - 1 - S // 2), radius=3 * S, outline=white, width=int(1.5 * S)))
    s['dot'] = shape(8, 8, lambda d, W, H: d.ellipse((0, 0, W - 1, H - 1), fill=white))
    s['btn'] = shape(44, 20, lambda d, W, H: d.rounded_rectangle((0, 0, W - 1, H - 1), radius=4 * S, fill=white))
    s['btnrim'] = shape(44, 20, lambda d, W, H: d.rounded_rectangle(
        (S // 2, S // 2, W - 1 - S // 2, H - 1 - S // 2), radius=4 * S, outline=white, width=int(1.5 * S)))
    return s


# --- a panel background ---------------------------------------------------------------------

def background():
    bg = vgrad(480, 272, (34, 38, 46, 255), (12, 14, 18, 255))
    # Fine horizontal brushing, composited rather than drawn in place, and regular so the PNG
    # still compresses.
    brush = Image.new('RGBA', (480, 272), (0, 0, 0, 0))
    bd = ImageDraw.Draw(brush)
    for y in range(0, 272, 3):
        bd.line((0, y, 479, y), fill=(255, 255, 255, 7))
    bg = Image.alpha_composite(bg, brush)
    glow = Image.new('RGBA', (480, 272), (0, 0, 0, 0))
    ImageDraw.Draw(glow).ellipse((-80, -140, 560, 120), fill=(255, 150, 40, 40))
    bg = Image.alpha_composite(bg, glow.filter(ImageFilter.GaussianBlur(40)))
    for sx, sy in ((6, 6), (468, 6), (6, 260), (468, 260)):      # screws
        ImageDraw.Draw(bg).ellipse((sx, sy, sx + 6, sy + 6), fill=(60, 66, 76, 255), outline=(20, 22, 26, 255))
    bg.convert('RGB').save(path('lab_bg.png'), optimize=True)


# --- full-colour pieces ---------------------------------------------------------------------

def step(lit, accent=False):
    w, h = 24, 30
    im = canvas(w, h)
    if lit:
        base = (255, 70, 60) if accent else (255, 150, 30)
        halo = Image.new('RGBA', im.size, (0, 0, 0, 0))
        ImageDraw.Draw(halo).rounded_rectangle((S * 2, S * 2, w * S - S * 2, h * S - S * 2), radius=5 * S, fill=base + (255,))
        im = Image.alpha_composite(im, halo.filter(ImageFilter.GaussianBlur(3 * S)))
        top = (255, 190, 170, 255) if accent else (255, 230, 170, 255)
        body = vgrad(w * S - 6 * S, h * S - 6 * S, top, base + (255,))
    else:
        body = vgrad(w * S - 6 * S, h * S - 6 * S, (58, 64, 76, 255), (26, 29, 36, 255))
    mask = Image.new('L', body.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, body.width - 1, body.height - 1), radius=4 * S, fill=255)
    im.paste(body, (3 * S, 3 * S), mask)
    ImageDraw.Draw(im).rounded_rectangle((3 * S, 3 * S, w * S - 3 * S - 1, h * S - 3 * S - 1),
                                         radius=4 * S, outline=(0, 0, 0, 200), width=S)
    gloss = Image.new('RGBA', im.size, (0, 0, 0, 0))
    ImageDraw.Draw(gloss).rounded_rectangle((5 * S, 5 * S, w * S - 5 * S, 12 * S), radius=3 * S,
                                            fill=(255, 255, 255, 70 if lit else 30))
    return down(Image.alpha_composite(im, gloss))


def rich_sprites():
    s = {'step_off': step(False), 'step_on': step(True), 'step_acc': step(True, True)}
    ph = canvas(30, 36)
    ImageDraw.Draw(ph).rounded_rectangle((3 * S, 3 * S, 27 * S, 33 * S), radius=6 * S,
                                         outline=(255, 255, 255, 230), width=2 * S)
    s['playhead'] = down(Image.alpha_composite(ph.filter(ImageFilter.GaussianBlur(2 * S)), ph))
    # A velocity bar: one tall glossy gradient; the page crops its bottom N pixels.
    vel = vgrad(14, 100, (255, 240, 180, 255), (255, 110, 20, 255))
    vd = ImageDraw.Draw(vel)
    vd.rectangle((0, 0, 3, 99), fill=(255, 255, 255, 60))
    vd.rectangle((12, 0, 13, 99), fill=(0, 0, 0, 60))
    s['vel'] = vel
    # The envelope's fill: a 4 px column fading out, cropped to each column's height.
    s['envfill'] = vgrad(4, 140, (80, 230, 255, 200), (20, 90, 160, 30))
    g = canvas(10, 10)
    ImageDraw.Draw(g).ellipse((0, 0, 10 * S - 1, 10 * S - 1), fill=(160, 250, 255, 255))
    s['glow'] = down(g.filter(ImageFilter.GaussianBlur(2 * S)))
    hd = canvas(16, 16)
    hdd = ImageDraw.Draw(hd)
    hdd.ellipse((0, 0, 16 * S - 1, 16 * S - 1), fill=(10, 20, 30, 255), outline=(160, 250, 255, 255), width=2 * S)
    hdd.ellipse((5 * S, 5 * S, 11 * S, 11 * S), fill=(255, 255, 255, 255))
    s['handle'] = down(hd)
    return s


# --- an analog VU -------------------------------------------------------------------------------

def vu():
    face = canvas(VU_W, VU_H)
    fd = ImageDraw.Draw(face)
    fd.rounded_rectangle((0, 0, VU_W * S - 1, VU_H * S - 1), radius=8 * S,
                         fill=(236, 222, 186, 255), outline=(40, 30, 20, 255), width=2 * S)
    cx, cy, r = VU_W * S / 2, VU_H * S * 1.18, VU_H * S * 0.98
    for i in range(21):
        a = math.radians(-50 + i * 5)
        r1, r2 = r * (0.86 if i % 5 else 0.80), r * 0.93
        fd.line((cx + r1 * math.sin(a), cy - r1 * math.cos(a), cx + r2 * math.sin(a), cy - r2 * math.cos(a)),
                fill=(200, 30, 20, 255) if i >= 15 else (40, 30, 20, 255),
                width=int(S * (1.6 if i % 5 == 0 else 1)))
    fd.arc((cx - r * 0.93, cy - r * 0.93, cx + r * 0.93, cy + r * 0.93), 295, 320, fill=(200, 30, 20, 255), width=3 * S)
    face = down(face)
    ImageDraw.Draw(face).text((VU_W / 2 - 8, VU_H - 34), 'VU', fill=(40, 30, 20, 255))
    face.save(path('vu_face.png'), optimize=True)

    strip = Image.new('RGBA', (VU_W, VU_H * VU_FRAMES), (0, 0, 0, 0))
    for f in range(VU_FRAMES):
        n = canvas(VU_W, VU_H)
        nd = ImageDraw.Draw(n)
        a = math.radians(-50 + 100 * f / (VU_FRAMES - 1))
        for (ox, oy), col, wid in (((3 * S, 3 * S), (0, 0, 0, 70), 3), ((0, 0), (20, 16, 12, 255), 2)):
            nd.line((cx + ox + r * 0.2 * math.sin(a), cy + oy - r * 0.2 * math.cos(a),
                     cx + ox + r * 0.95 * math.sin(a), cy + oy - r * 0.95 * math.cos(a)),
                    fill=col, width=int(wid * S))
        strip.paste(down(n), (0, f * VU_H))
    strip.save(path('vu_needle.png'), optimize=True)


# --- flipbooks: animation the device can play --------------------------------------------------

LOGO_W, LOGO_H, LOGO_FRAMES = 220, 40, 16
SPIN, SPIN_FRAMES = 32, 16


def logo_strip():
    """The HoSTage logo (tools/ctrl49/hostage_logo.png, an alpha mask) in orange, with a band of
    light sweeping across it once per loop: 16 frames the device steps through."""
    mask = Image.open(os.path.join(HERE, '..', 'hostage_logo.png')).convert('RGBA').split()[3]
    mask = mask.resize((LOGO_W, LOGO_H), Image.LANCZOS)
    strip = Image.new('RGBA', (LOGO_W, LOGO_H * LOGO_FRAMES), (0, 0, 0, 0))
    for f in range(LOGO_FRAMES):
        colour = Image.new('RGBA', (LOGO_W, LOGO_H), (255, 148, 8, 255))
        sheen = Image.new('L', (LOGO_W, LOGO_H), 0)
        centre = -60 + (LOGO_W + 120) * f / (LOGO_FRAMES - 1)
        ImageDraw.Draw(sheen).polygon([(centre - 18, LOGO_H), (centre + 2, 0), (centre + 26, 0), (centre + 6, LOGO_H)], fill=235)
        sheen = sheen.filter(ImageFilter.GaussianBlur(4))
        colour = Image.composite(Image.new('RGBA', colour.size, (255, 244, 220, 255)), colour, sheen)
        colour.putalpha(mask)
        strip.paste(colour, (0, f * LOGO_H))
    strip.save(path('logo_strip.png'), optimize=True)


def spinner_strip():
    """A loading spinner, white so the device can tint it: a ring of 12 dashes, brightest at
    the head, rotated one step per frame. Rotation is baked — the device cannot rotate."""
    strip = Image.new('RGBA', (SPIN, SPIN * SPIN_FRAMES), (255, 255, 255, 0))
    for f in range(SPIN_FRAMES):
        im = canvas(SPIN, SPIN)
        d = ImageDraw.Draw(im)
        c = SPIN * S / 2
        for k in range(12):
            a = 2 * math.pi * (k / 12 + f / SPIN_FRAMES)
            alpha = int(255 * (k + 1) / 12)
            d.line((c + 7 * S * math.sin(a), c - 7 * S * math.cos(a), c + 14 * S * math.sin(a), c - 14 * S * math.cos(a)),
                   fill=(255, 255, 255, alpha), width=3 * S)
        strip.paste(down(im), (0, f * SPIN))
    strip.save(path('spinner_strip.png'), optimize=True)


def gif_to_strip(gif, out, width=None):
    """Any GIF as a vertical flipbook PNG: frame N at y = N * height. Prints what the device
    needs to know — frame size, frame count, and what it costs in device memory."""
    from PIL import ImageSequence
    frames = [f.convert('RGBA') for f in ImageSequence.Iterator(Image.open(gif))]
    w, h = frames[0].size
    if width:
        h, w = round(h * width / w), width
        frames = [f.resize((w, h), Image.LANCZOS) for f in frames]
    strip = Image.new('RGBA', (w, h * len(frames)), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        strip.paste(f, (0, i * h))
    strip.save(out, optimize=True)
    print(f'{out}: {len(frames)} frames of {w}x{h}, {os.path.getsize(out)} bytes, '
          f'decodes to ~{w * h * 4 * len(frames) // 1024} KB on the device')


# --- the stress page's memory block ------------------------------------------------------------

def stress_block():
    """256x1024 decodes to 1 MB whatever the PNG weighs. Bands of colour, so a crop of it on the
    screen shows that it decoded, and regular, so the PNG stays small to upload."""
    im = Image.new('RGB', (256, 1024))
    d = ImageDraw.Draw(im)
    for band in range(32):
        hue = band * 11 % 32
        d.rectangle((0, band * 32, 255, band * 32 + 31),
                    fill=(80 + hue * 5, 120 + (hue * 3) % 100, 200 - hue * 4))
    im.save(path('stress_block.png'), optimize=True)


if __name__ == '__main__':
    import sys
    if len(sys.argv) >= 4 and sys.argv[1] == '--gif':
        width = int(sys.argv[sys.argv.index('--width') + 1]) if '--width' in sys.argv else None
        gif_to_strip(sys.argv[2], sys.argv[3], width)
        sys.exit(0)
    flat = pack(flat_sprites(), 'surface_atlas.png')
    background()
    rich = pack(rich_sprites(), 'rich_atlas.png')
    vu()
    stress_block()
    logo_strip()
    spinner_strip()
    write_tables('Hostage_Showcase.lua', [lua_table('SPR', flat), lua_table('R', rich)])
    write_tables('Hostage_Stress.lua', [lua_table('SPR', flat)])
    for f in ('surface_atlas.png', 'rich_atlas.png', 'lab_bg.png', 'vu_face.png', 'vu_needle.png',
              'stress_block.png', 'logo_strip.png', 'spinner_strip.png'):
        im = Image.open(path(f))
        print(f'{f:18s} {im.size[0]:4d}x{im.size[1]:<5d} {os.path.getsize(path(f)):7d} bytes  '
              f'decodes to ~{im.size[0] * im.size[1] * 4 // 1024} KB')
