// genCsharp.mjs — generate a buildable C# (NativeAOT) handler module from a panel's C# scripts.
//
// Mirror of genCpp.mjs, for the C# compile-at-export path. Output (<outDir>):
//   • CeRuntime.cs                       — the interop + user-facing surface (copied from this dir)
//   • Handlers.<sanitizedId>.cs (per script) — the user's source wrapped in `static class Script_<id>`
//   • HandlerRegistry.Registration.cs    — the generated `GeneratedRegistration.RegisterAll()` partial
//                                           that adds each (scriptId, eventId) -> Script_<id>.<event>
//   • ce_handlers_csharp.csproj          — NativeAOT shared-library project (size-tuned)
//
// The project/assembly name is `ce_handlers_csharp`, so `dotnet publish` emits
// `ce_handlers_csharp.<dll|dylib|so>` — exactly the file NativeHandlerEngine::moduleFileName() loads.
//
// BUILD STATUS / REQUIREMENTS — BUILD-UNVERIFIED SCAFFOLD:
//   • Requires the .NET 9 or 10 SDK PLUS the platform native toolchain NativeAOT shells out to
//     (Linux: clang + the usual binutils/zlib dev packages; macOS: Xcode command-line tools;
//      Windows: MSVC build tools / Desktop C++ workload).
//   • Build is PER-OS: NativeAOT cannot cross-compile across OSes. Run `publishCommand(rid)` on a host
//     matching the target OS (e.g. linux-x64 on Linux, osx-arm64 on macOS, win-x64 on Windows).
//   • Expected module size is ~1.5-4 MB (the GC + a trimmed runtime are baked in; see NativeHandlerAbi.h).
//   • OUTPUT NAMING: on Linux, NativeLib=Shared emits `ce_handlers_csharp.so` (NO `lib` prefix), which is
//     exactly what the host wants. On Windows it is `ce_handlers_csharp.dll` and on macOS
//     `ce_handlers_csharp.dylib` — both already match. If a future SDK emits a `lib`-prefixed name, the
//     export pipeline must rename it to `ce_handlers_csharp.<ext>` before bundling next to the plugin.

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// A stable C# identifier fragment from a script id.
function sanitize(id) {
  return String(id).replace(/[^A-Za-z0-9_]/g, '_');
}

// C# string literal — JSON string escaping is valid for our ids/event names (no surprises in C# verbatim
// vs JSON for the ASCII identifiers + dotted ids we use).
function csstr(s) {
  return JSON.stringify(String(s));
}

export function generateCsharpModule({ scripts, outDir, abiInfo }) {
  mkdirSync(outDir, { recursive: true });

  const usable = (scripts ?? []).filter(
    (s) => s?.enabled !== false && typeof s?.source === 'string' && s.source.trim() && s.event,
  );

  // 1) Copy the runtime verbatim so the generated project compiles against the exact interop surface.
  const runtimeSrc = readFileSync(path.join(__dirname, 'CeRuntime.cs'), 'utf8');
  writeFileSync(path.join(outDir, 'CeRuntime.cs'), runtimeSrc);

  // 2) Per-script wrapper: the user writes `static void onValueChanged(CeContext ctx, CeEvent e) {...}`
  //    and we drop their source inside `static class Script_<id>` in the Ce.Handlers namespace. Two
  //    controls can both define onValueChanged without colliding (distinct classes).
  for (const s of usable) {
    const cls = `Script_${sanitize(s.id)}`;
    const body = `// GENERATED by genCsharp.mjs — do not edit. Script: ${s.name ?? s.id}
using Ce;

namespace Ce.Handlers
{
    // User handler source for script id ${csstr(s.id)}. Methods must be:
    //   static void <eventName>(CeContext ctx, CeEvent e) { ... }
    static class ${cls}
    {
${s.source}
    }
}
`;
    writeFileSync(path.join(outDir, `Handlers.${sanitize(s.id)}.cs`), body);
  }

  // 3) Registration partial: implements GeneratedRegistration.RegisterAll(), adding each
  //    (scriptId, eventId) -> Script_<id>.<event> to the HandlerRegistry. Always emitted (empty body if
  //    no handlers) so the partial in CeRuntime.cs has its implementation and the module compiles.
  const regLines = usable
    .map((s) => {
      const cls = `Script_${sanitize(s.id)}`;
      return `            HandlerRegistry.Add(${csstr(s.id)}, ${csstr(s.event)}, Ce.Handlers.${cls}.${s.event});`;
    })
    .join('\n');

  const registration = `// GENERATED by genCsharp.mjs — do not edit. Populates the dispatch registry.
namespace Ce
{
    internal static partial class GeneratedRegistration
    {
        public static partial void RegisterAll()
        {
${regLines || '            // no enabled handlers'}
        }
    }
}
`;
  writeFileSync(path.join(outDir, 'HandlerRegistry.Registration.cs'), registration);

  // 4) NativeAOT shared-library project. Assembly name pinned to ce_handlers_csharp so the published
  //    native lib is ce_handlers_csharp.<ext>. Size knobs trim the ~MB-scale baked-in runtime.
  const targetFramework = (abiInfo && abiInfo.targetFramework) || 'net9.0';
  const csproj = `<!-- GENERATED by genCsharp.mjs — do not edit. NativeAOT shared-library handler module. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>${targetFramework}</TargetFramework>
    <!-- Pins the output file name to ce_handlers_csharp.<dll|dylib|so> (the host's expected name). -->
    <AssemblyName>ce_handlers_csharp</AssemblyName>
    <RootNamespace>Ce</RootNamespace>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- NativeAOT shared library. -->
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>

    <!-- Size / determinism knobs (shrink the baked-in runtime; no globalization/ICU, no stack traces). -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <AutoreleasePoolSupport>false</AutoreleasePoolSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CeRuntime.cs" />
    <Compile Include="HandlerRegistry.Registration.cs" />
    <Compile Include="Handlers.*.cs" />
  </ItemGroup>

</Project>
`;
  writeFileSync(path.join(outDir, 'ce_handlers_csharp.csproj'), csproj);

  return {
    dir: outDir,
    moduleName: 'ce_handlers_csharp',
    handlerCount: usable.length,
    // Per-OS NativeAOT publish. `rid` is a .NET runtime identifier matching the BUILD host's OS, e.g.
    // 'linux-x64', 'osx-arm64', 'win-x64'. Output: ce_handlers_csharp.<so|dylib|dll>.
    publishCommand(rid) {
      return `dotnet publish -c Release -r ${rid} -p:NativeLib=Shared`;
    },
  };
}
