// genCsharp.mjs — generate a buildable C# handler module from a panel's C# scripts, using the
// HOSTED-CoreCLR path (NOT NativeAOT). See native-handlers-design.md §C# for the why.
//
// Why hosted-CoreCLR and not NativeAOT: NativeAOT-on-Windows needs the MSVC CRT + Windows SDK import
// libraries, which are Microsoft-proprietary and NOT redistributable — so we cannot ship a
// no-Visual-Studio NativeAOT path to a user's machine. Instead:
//   • Roslyn (`dotnet publish`, pure IL emission — NO native linker, NO MSVC, NO Windows SDK) compiles
//     the user's C# + CeRuntime.cs into a managed `ce_managed.dll`.
//   • A self-contained publish bundles a trimmed-capable CoreCLR (MIT, freely redistributable) beside it.
//   • A tiny C shim (CeHost.c, built with the bundled llvm-mingw clang — no MSVC) exports the flat C ABI
//     and boots that CoreCLR via hostfxr, forwarding every call to the managed [UnmanagedCallersOnly]
//     entry points on Ce.Exports.
//
// Output (<outDir>):
//   • CeRuntime.cs                       — interop + user-facing surface (copied from this dir)
//   • Handlers.<sanitizedId>.cs (per script) — the user's source wrapped in `sealed partial Script_<id>`
//   • HandlerRegistry.Registration.cs    — generated GeneratedRegistration.RegisterAll() partial
//   • Program.cs                         — no-op entry point (hostfxr command-line init needs one; never run)
//   • roots.xml                          — trimmer root descriptor (keeps the handler assembly whole)
//   • ce_managed.csproj                  — self-contained CoreCLR project (assembly name `ce_managed`)
//   • CeHost.c + hosting/*.h             — the native hosting shim + vendored hostfxr headers (copied)
//
// The full build is two steps (run by index.mjs):
//   1) dotnet publish -c Release -r <rid> --self-contained true -o pub   (Roslyn → ce_managed.dll + CoreCLR)
//   2) <clang> -x c CeHost.c -o pub/ce_handlers_csharp.<ext>             (the shim, into the publish dir)
// then the whole `pub/` dir ships next to the plugin (the host loads ce_handlers_csharp.<ext>; the shim
// self-locates hostfxr + ce_managed.dll beside itself).
//
// VERIFIED 2026-06 on .NET 10 (linux-x64): `verify-csharp.mjs` runs the real publish + shim build and
// dispatches a C# handler through the flat ABI that calls back into the host (out=21, log='ran').

import { mkdirSync, writeFileSync, readFileSync, copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// A stable C# identifier fragment from a script id.
function sanitize(id) {
  return String(id).replace(/[^A-Za-z0-9_]/g, '_');
}

// C# string literal — JSON string escaping is valid for our ids/event names (ASCII identifiers + dotted ids).
function csstr(s) {
  return JSON.stringify(String(s));
}

export function generateCsharpModule({ scripts, outDir, abiInfo }) {
  mkdirSync(outDir, { recursive: true });

  const usable = (scripts ?? []).filter(
    (s) => s?.enabled !== false && typeof s?.source === 'string' && s.source.trim() && s.event,
  );

  // 1) Copy the managed runtime + the native shim + the vendored hosting headers verbatim.
  copyFileSync(path.join(__dirname, 'CeRuntime.cs'), path.join(outDir, 'CeRuntime.cs'));
  copyFileSync(path.join(__dirname, 'CeHost.c'), path.join(outDir, 'CeHost.c'));
  const hostingOut = path.join(outDir, 'hosting');
  mkdirSync(hostingOut, { recursive: true });
  for (const h of ['hostfxr.h', 'coreclr_delegates.h'])
    copyFileSync(path.join(__dirname, 'hosting', h), path.join(hostingOut, h));

  // 2) Per-script wrapper: the user writes `void onValueChanged(CeContext ctx, CeEvent e) {...}` (an
  //    INSTANCE method, matching the editor skeleton) inside a sealed partial Script_<id>. Two controls
  //    can both define onValueChanged without colliding (distinct classes).
  for (const s of usable) {
    const cls = `Script_${sanitize(s.id)}`;
    const body = `// GENERATED by genCsharp.mjs — do not edit. Script: ${s.name ?? s.id}
using Ce;

namespace Ce.Handlers
{
    // User handler source for script id ${csstr(s.id)}. Methods are instance methods:
    //   void <eventName>(CeContext ctx, CeEvent e) { ... }
    sealed partial class ${cls}
    {
${s.source}
    }
}
`;
    writeFileSync(path.join(outDir, `Handlers.${sanitize(s.id)}.cs`), body);
  }

  // 3) Registration partial: each Script_<id> gets a partial self-register method (it lives INSIDE the
  //    class so it can bind the private instance handler as a delegate); RegisterAll() calls them all.
  const partials = usable
    .map((s) => {
      const cls = `Script_${sanitize(s.id)}`;
      return `namespace Ce.Handlers
{
    sealed partial class ${cls}
    {
        internal static void __ce_register()
            => global::Ce.HandlerRegistry.Add(${csstr(s.id)}, ${csstr(s.event)}, new ${cls}().${s.event});
    }
}`;
    })
    .join('\n');
  const regLines = usable
    .map((s) => `            Ce.Handlers.Script_${sanitize(s.id)}.__ce_register();`)
    .join('\n');

  const registration = `// GENERATED by genCsharp.mjs — do not edit. Populates the dispatch registry.
${partials}

namespace Ce
{
    internal static partial class GeneratedRegistration
    {
        public static partial void RegisterAll()
        {
${regLines || '            // no enabled handlers'}
        }
    }
}
`;
  writeFileSync(path.join(outDir, 'HandlerRegistry.Registration.cs'), registration);

  // 4) No-op entry point. hostfxr command-line init (used because it supports self-contained components,
  //    which initialize_for_runtime_config does not) needs the assembly to have an entry point. We never
  //    run Main — the shim only gets a runtime delegate and resolves the [UnmanagedCallersOnly] exports.
  writeFileSync(
    path.join(outDir, 'Program.cs'),
    `// GENERATED by genCsharp.mjs — no-op entry point (the native shim inits the runtime via hostfxr and
// never runs Main; it only exists so a self-contained publish has an entry point).
namespace Ce { internal static class Program { static void Main() { } } }
`,
  );

  // 5) Trimmer root descriptor — preserve the whole (tiny) handler assembly so the trimmer never prunes
  //    the [UnmanagedCallersOnly] exports / user handlers it can't see are reached from native code.
  writeFileSync(
    path.join(outDir, 'roots.xml'),
    `<!-- GENERATED by genCsharp.mjs. Keep the handler assembly whole; the trimmer can't see the
     [UnmanagedCallersOnly] entry points are reachable (they're called from the native host shim). -->
<linker>
  <assembly fullname="ce_managed" preserve="all" />
</linker>
`,
  );

  // 6) The self-contained CoreCLR project. AssemblyName pinned to ce_managed so the shim's hard-coded
  //    "ce_managed.dll" / "Ce.Exports, ce_managed" resolve. Self-contained so a trimmed CoreCLR ships in
  //    `pub/` beside the shim (no machine-wide .NET needed on the END-USER's box).
  //    Trimming is OFF by default (PublishTrimmed=false): the untrimmed self-contained layout is the
  //    proven-correct baseline (~80 MB). Size-trim is a tunable follow-up — see native-handlers-design.md
  //    §C# (full `link` trim breaks UnmanagedCallersOnly resolution / the hostfxr component-activator
  //    path unless those roots are added; tracked as a size optimization, not correctness).
  const targetFramework = (abiInfo && abiInfo.targetFramework) || 'net10.0';
  const csproj = `<!-- GENERATED by genCsharp.mjs — do not edit. Self-contained CoreCLR handler assembly. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>${targetFramework}</TargetFramework>
    <!-- Pins the assembly to ce_managed.dll (the shim loads it + resolves Ce.Exports by this name). -->
    <AssemblyName>ce_managed</AssemblyName>
    <RootNamespace>Ce</RootNamespace>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Ship a self-contained CoreCLR in pub/ (no user .NET install). Untrimmed = proven baseline. -->
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>

    <!-- Determinism / size knobs that don't affect hosting correctness. -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <AutoreleasePoolSupport>false</AutoreleasePoolSupport>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="roots.xml" />
  </ItemGroup>

  <!-- The SDK auto-includes every .cs in this dir (CeRuntime.cs + the generated files + Program.cs),
       which is exactly what we want. Do NOT list them explicitly — that trips NETSDK1022. -->

</Project>
`;
  writeFileSync(path.join(outDir, 'ce_managed.csproj'), csproj);

  // The publish output dir (relative to outDir) where ce_managed.dll + the CoreCLR land; the shim is
  // compiled INTO it and the whole dir ships next to the plugin.
  const publishSubdir = 'pub';

  return {
    dir: outDir,
    moduleName: 'ce_handlers_csharp',
    managedName: 'ce_managed',
    handlerCount: usable.length,
    publishSubdir,
    shimSource: path.join(outDir, 'CeHost.c'),
    hostingIncludeDir: hostingOut,
    // Roslyn publish → self-contained CoreCLR + ce_managed.dll in `pub/`. `rid` matches the BUILD host's
    // OS/arch (linux-x64, win-x64, osx-arm64). No NativeAOT, no native linker — pure IL emission.
    publishCommand(rid) {
      return `dotnet publish -c Release -r ${rid} --self-contained true -o ${publishSubdir}`;
    },
  };
}
