// genJava.mjs — generate a buildable Java handler module from a panel's Java scripts, using the
// HOSTED-JVM path (javac bytecode + a jlink'd JRE shipped in the plugin + a JNI shim), NOT GraalVM
// native-image. See native-handlers-design.md §Java.
//
// Why hosted-JVM and not GraalVM native-image: native-image needs a 8–16 GB / 30 s–5 min closed-world
// rebuild on EVERY export plus the whole GraalVM JDK on the dev machine. Instead the user's handlers
// compile to ordinary bytecode with `javac` (seconds), and a small ~40 MB JRE produced by `jlink` ships
// INSIDE the plugin. The native shim `ce_java_shim.c` (built with the bundled clang) boots that JRE via
// the JNI Invocation API and forwards the flat C ABI. This mirrors the C# hosted-CoreCLR path.
//
// Output (<outDir>):
//   • CeRuntime.java            — runtime + JNI interop + flat-ABI entry points (copied from this dir)
//   • Script_<id>.java (each)   — the user's handler wrapped in `final class Script_<id>`
//   • GeneratedRegistry.java    — <clinit> registers each (scriptId, event) -> handler
//   • ce_java_shim.c            — the JNI hosting shim (copied)
//   • NativeHandlerAbi.h        — copied next to the shim so its #include resolves
// Build (run by index.mjs / verify-java.mjs via buildPlan(tools)):
//   1) javac the sources -> classes/         2) jar -> ce_handlers_java.jar
//   3) jlink a minimal JRE -> jre/            4) clang the shim -> ce_handlers_java.<ext>
// then the shim + jar + jre/ ship next to the plugin (the shim self-locates jre/ + the jar beside it).
//
// VERIFIED 2026-06 on JDK 21 (linux-x64): the emitted sources compile, jlink yields a ~39 MB JRE, and
// the shared host harness loads ce_handlers_java.so, boots the JVM, and dispatches a Java handler that
// calls back into the host (out=21, log='ran').

import { mkdirSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));

// A stable Java identifier fragment from a script id.
function sanitize(id) {
  return String(id).replace(/[^A-Za-z0-9_]/g, '_');
}
// Java string literal escaping (JSON escaping is valid for our ASCII ids/event names).
function jstr(s) {
  return JSON.stringify(String(s));
}
// Indent every line of `src` by `n` spaces (to nest the user method inside a class).
function indent(src, n) {
  const pad = ' '.repeat(n);
  return String(src).split('\n').map((l) => (l.length ? pad + l : l)).join('\n');
}
function copyAlongside(name, outDir) {
  const src = path.join(HERE, name);
  const dst = path.join(outDir, name);
  if (path.resolve(src) === path.resolve(dst)) return;
  if (existsSync(src)) copyFileSync(src, dst);
}

const MODULE = 'ce_handlers_java';
const JAR = `${MODULE}.jar`;

export function generateJavaModule({ scripts, outDir, abiInfo = {} }) {
  mkdirSync(outDir, { recursive: true });

  const usable = (scripts ?? []).filter(
    (s) => s?.enabled !== false && typeof s?.source === 'string' && s.source.trim() && s.event,
  );

  // 1) Per-script wrapper classes — each user method wrapped in `final class Script_<id>` with a
  //    singleton INSTANCE so the registry can take an instance method reference (closed-world-free; this
  //    is now ordinary bytecode, but keeping the shape matches the C++/C# generators).
  const sources = [];
  for (const s of usable) {
    const cls = `Script_${sanitize(s.id)}`;
    const body = `// GENERATED by genJava.mjs — do not edit. Script: ${s.name ?? s.id}
// CeContext / CeEvent / CeRuntime are top-level package-private types in this same (default) package,
// so the handler names them unqualified:  void onValueChanged(CeContext ctx, CeEvent e) { ... }
final class ${cls} {
    static final ${cls} INSTANCE = new ${cls}();
${indent(s.source, 4)}
}
`;
    writeFileSync(path.join(outDir, `${cls}.java`), body);
    sources.push(`${cls}.java`);
  }

  // 2) Generated registry: <clinit> registers every (scriptId, event) -> handler. CeRuntime.init()
  //    forces it to load via Class.forName("GeneratedRegistry").
  const registrations = usable
    .map((s) => `        CeRuntime.register(${jstr(s.id)}, ${jstr(s.event)}, Script_${sanitize(s.id)}.INSTANCE::${s.event});`)
    .join('\n');
  writeFileSync(
    path.join(outDir, 'GeneratedRegistry.java'),
    `// GENERATED by genJava.mjs — do not edit. Dispatch registry.
final class GeneratedRegistry {
    static { register(); }
    static void register() {
${registrations || '        // (no handlers in this panel)'}
    }
    private GeneratedRegistry() {}
}
`,
  );

  // 3) Copy the runtime + the JNI shim, and NativeHandlerAbi.h next to the shim (its #include resolves).
  copyAlongside('CeRuntime.java', outDir);
  copyAlongside('ce_java_shim.c', outDir);
  const abiHeaderDir = abiInfo.abiHeaderDir ?? abiInfo.dir;
  if (abiHeaderDir && existsSync(path.join(abiHeaderDir, 'NativeHandlerAbi.h'))) {
    copyFileSync(path.join(abiHeaderDir, 'NativeHandlerAbi.h'), path.join(outDir, 'NativeHandlerAbi.h'));
  }

  writeFileSync(path.join(outDir, 'BUILD.md'), buildMarkdown());

  return {
    dir: outDir,
    moduleName: MODULE,
    jarName: JAR,
    handlerCount: usable.length,
    javaSources: ['CeRuntime.java', 'GeneratedRegistry.java', ...sources],

    /**
     * Build commands for this module, given resolved tool paths.
     *   tools = { javac, jar, jlink, cc, jniIncludeDir, abiDir, ext, modules? }
     * Returns { compile:[...], jlink:[...], shim:[...], artifacts:{ files:[...], dirs:[...] } }.
     * Run compile -> jlink -> shim in order (jlink + shim are independent and may run in parallel).
     */
    buildPlan(tools) {
      const ext = tools.ext || (process.platform === 'win32' ? '.dll' : process.platform === 'darwin' ? '.dylib' : '.so');
      const osInc = process.platform === 'win32' ? 'win32' : process.platform === 'darwin' ? 'darwin' : 'linux';
      const jniInc = tools.jniIncludeDir;
      const q = (p) => `"${p}"`;
      const srcs = this.javaSources.map((f) => q(path.join(outDir, f))).join(' ');
      // java.base covers Collections/String/Math/regex/time — enough for typical handlers. Extra modules
      // can be added by the caller (tools.modules) if a panel needs them.
      const modules = tools.modules || 'java.base';
      const cflags = process.platform === 'win32' ? '' : '-fPIC';
      const ldl = process.platform === 'win32' ? '' : '-ldl';
      return {
        compile: [
          `${q(tools.javac)} -d ${q(path.join(outDir, 'classes'))} ${srcs}`,
          `${q(tools.jar)} --create --file ${q(path.join(outDir, JAR))} -C ${q(path.join(outDir, 'classes'))} .`,
        ],
        jlink: [
          `${q(tools.jlink)} --add-modules ${modules} --output ${q(path.join(outDir, 'jre'))} ` +
            `--strip-debug --no-header-files --no-man-pages --compress zip-6`,
        ],
        shim: [
          `${q(tools.cc)} -x c -shared ${cflags} -O2 -fvisibility=hidden ` +
            `-I ${q(tools.abiDir)} -I ${q(jniInc)} -I ${q(path.join(jniInc, osInc))} ` +
            `${q(path.join(outDir, 'ce_java_shim.c'))} -o ${q(path.join(outDir, MODULE + ext))} ${ldl}`,
        ],
        artifacts: { files: [`${MODULE}${ext}`, JAR], dirs: ['jre'] },
      };
    },
  };
}

function buildMarkdown() {
  return `# Building ${MODULE} (hosted-JVM: javac + jlink + JNI shim)

JDK 21 (\`javac\` + \`jar\` + \`jlink\`) + a C compiler (the bundled llvm-mingw clang). NO GraalVM,
no native-image, no multi-GB closed-world rebuild. The user's handlers are ordinary bytecode; a small
jlink'd JRE (~40 MB) ships inside the plugin and the shim boots it via JNI.

Ships next to the plugin: \`${MODULE}.<ext>\` (the shim, what the host opens) + \`${JAR}\` (handler
bytecode) + \`jre/\` (the jlink'd runtime). The shim self-locates \`jre/\` + the jar beside itself.

1. \`javac -d classes *.java\`
2. \`jar --create --file ${JAR} -C classes .\`
3. \`jlink --add-modules java.base --output jre --strip-debug --no-header-files --no-man-pages --compress=2\`
4. \`clang -x c -shared -fPIC -I <abi> -I <jdk>/include -I <jdk>/include/<os> ce_java_shim.c -o ${MODULE}.<ext>\`
`;
}
