// components.mjs — QA-01: one of every component type, at its authored defaults.
//
// What this sheet is for: the cheapest possible answer to "did anything stop rendering". Every
// component the editor can make, on one screen, captioned, in a fixed order. You open it, you
// look, and anything blank or wrong is the thing to fix. No clicking, no setup, no device.
//
// What makes it worth generating rather than drawing once: it is built from COMPONENT_TYPES, so
// the sheet cannot fall behind the model. Add a component and it appears here on the next
// regeneration — and until you file it under a group below, `qaPanels.test.js` fails. That is the
// whole point. A checklist that has to be updated by hand is a checklist that is already wrong.
//
// Defaults ON PURPOSE. This sheet asks "does the authored default look right", which is the state
// a user meets first and the one nobody ever checks. Non-default property work is QA-02's job.

import { COMPONENT_TYPES, createControl } from '../../../../CE/web/src/CE_Application/models/componentTypes.js';
import { createPanel } from '../../../../CE/web/src/CE_Application/stores/panelModel.js';
import { flowGroups, styleSheet } from '../layout.mjs';

/**
 * Every component type, filed by what a user would go looking for it under — not by which section
 * it carries, which is an implementation fact. The test asserts this covers COMPONENT_TYPES
 * exactly: no type in two groups, no type in none, no name here that is no longer a type.
 */
export const GROUPS = [
  {
    title: 'Structure — the furniture a panel is built out of',
    types: ['Background', 'Container', 'Group', 'TabContainer', 'ScrollArea', 'Image', 'Shape', 'TestBox'],
  },
  {
    title: 'Text & numeric entry',
    types: ['Label', 'TextInput', 'Number', 'Range'],
  },
  {
    title: 'Buttons — every trigger variant, because they differ only in behaviour',
    types: ['Button', 'MomentaryButton', 'ToggleButton', 'TimedButton', 'OneShotButton', 'CyclicButton', 'RadioButtonGroup'],
  },
  {
    title: 'Selection',
    types: ['Combobox', 'Listbox', 'Numpad'],
  },
  {
    title: 'Continuous controls',
    types: ['Slider', 'Knob', 'Crossfader', 'Ribbon', 'PitchWheel', 'ModWheel', 'VectorJoystick'],
  },
  {
    title: 'Displays — the read-only half, where "value arrived" becomes visible',
    types: ['LcdDisplay', 'PixelDisplay', 'Meter', 'ProgressBar'],
  },
  {
    title: 'Modulation & mapping',
    types: ['Macro', 'Constellation', 'Timbre', 'Router', 'Turing', 'Kinetic', 'Orbit', 'Envelope', 'Matrix', 'Constraint'],
  },
  {
    title: 'Performance & MIDI',
    types: ['Keyboard', 'StepSequencer', 'ChordPad', 'Arp', 'NoteRibbon', 'DrumPads', 'Phrase', 'Looper', 'Setlist', 'Harmoniser', 'Recorder', 'SplitZone', 'Panic', 'Transport'],
  },
  {
    title: 'Custom components — the empty shell; QA-07 covers real packages',
    types: ['CustomComponent'],
  },
];

const NOTES = `QA-01 — every component type at its authored defaults.

Generated by tools/scripts/qa/make-qa-panels.mjs. Do not hand-edit: regenerate instead, or your
changes vanish the next time a component is added.

How to read it
  Each control sits under a caption naming its type. Everything here is at the default a user
  gets when they drag the component onto a blank canvas — nothing is configured.

What a failure looks like
  - a blank cell                      the renderer threw, or draws nothing at defaults
  - a control the size of its caption  the type's defaultOverrides lost its Transform
  - text reading "Label" or "Button"   correct: that IS the authored default
  - a cell that overlaps its neighbour the component ignores its Transform width/height

What this sheet does NOT prove
  Nothing here is interactive, bound, or scripted. A component can render perfectly at defaults
  and still be broken the moment it is dragged, bound to a device, or driven from a script.
  That is QA-03 through QA-06.`;

export function buildComponentsSheet() {
  const panel = createPanel('QA-01 Components');

  const groups = GROUPS.map((group) => ({
    title: group.title,
    cells: group.types.map((type) => ({
      caption: type,
      // A stable id per type, so a diff between two regenerations is a real change rather than
      // a renumbering. Same reason the sheet is committed at all.
      control: createControl(type, { Core: { id: `qa01_${type}`, name: `qa01_${type}` } }),
    })),
  }));

  const { controls, height } = flowGroups(groups);
  panel.controls = controls;
  panel.height = height;

  return styleSheet(panel, { title: 'QA-01 — every component type at authored defaults', notes: NOTES });
}

/** Every type this sheet places. Used by the coverage ratchet. */
export function coveredTypes() {
  return GROUPS.flatMap((group) => group.types);
}

/** Declared so the test can compare against the model rather than against a copy of it. */
export function allTypes() {
  return Object.keys(COMPONENT_TYPES);
}
