# Generates Ctrl49EmbeddedAssets.cpp: the CTRL49 bridge's Lua pages, filmstrip PNG,
# default assignment/preset bank, and the GAIA device profile as byte arrays, so
# Ctrl49Bridge.exe is fully self-contained (no loose files beside the exe).
#
# Invoked at build time:
#   cmake -DROOT=<repo root> -DOUT=<generated .cpp> -P tools/ctrl49/embed_assets.cmake

if(NOT DEFINED ROOT OR NOT DEFINED OUT)
    message(FATAL_ERROR "embed_assets.cmake requires -DROOT= and -DOUT=")
endif()

set(CONTENT "// Generated by tools/ctrl49/embed_assets.cmake — do not edit.\n")
string(APPEND CONTENT "#include \"ControlSurface/Ctrl49EmbeddedAssets.h\"\n\n")
string(APPEND CONTENT "namespace ceditor::ctrl49::assets {\n\n")

function(embed_file symbol path)
    file(READ "${path}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND CONTENT "const unsigned char ${symbol}[] = {${bytes}};\n")
    string(APPEND CONTENT "const unsigned int ${symbol}Size = sizeof(${symbol});\n\n")
    set(CONTENT "${CONTENT}" PARENT_SCOPE)
endfunction()

embed_file(kBridgePageLua      "${ROOT}/tools/ctrl49/CEditor_Bridge.lua")
embed_file(kKnobPageLua        "${ROOT}/tools/ctrl49/CEditor_MultiKnob.lua")
embed_file(kPresetListLua      "${ROOT}/tools/ctrl49/CEditor_PresetList.lua")
embed_file(kKnobStripPng       "${ROOT}/tools/ctrl49/knob_strip.png")
embed_file(kDefaultAssignment  "${ROOT}/tools/ctrl49/bridge-default.assignment.json")
embed_file(kDefaultPresetBank  "${ROOT}/tools/ctrl49/gaia-patches.presetbank.json")
embed_file(kGaiaProfileJson    "${ROOT}/CE/profiles/test/roland-gaia.ceditor-device.json")

string(APPEND CONTENT "} // namespace ceditor::ctrl49::assets\n")

file(WRITE "${OUT}" "${CONTENT}")
message(STATUS "embedded CTRL49 assets -> ${OUT}")
