const COMPONENT_BACKGROUND_ORDER_PATHS = [
  'Background.mode',
  'Background.Fill.mode',
  'Background.Fill.layerOrder',
];

const COMPONENT_BACKGROUND_SOLID_PATHS = [
  'Background.Fill.colour',
  'Background.Fill.solidEnabled',
  'Background.Fill.solidBlend',
  'Background.Fill.solidClipMode',
  'Background.Fill.solidMuted',
];

const COMPONENT_BACKGROUND_GRADIENT_PATHS = [
  'Background.Fill.gradientEnabled',
  'Background.Fill.gradientOpacity',
  'Background.Fill.gradientName',
  'Background.Fill.gradientBlend',
  'Background.Fill.gradientClipMode',
  'Background.Fill.gradientMuted',
  'Background.Fill.gradient',
];

const COMPONENT_BACKGROUND_IMAGE_PATHS = [
  'Background.Fill.imageEnabled',
  'Background.Fill.imageMuted',
  'Background.Fill.imageSrc',
  'Background.Fill.imageOpacity',
  'Background.Fill.imageFit',
  'Background.Fill.imageAlign',
  'Background.Fill.imageOffsetX',
  'Background.Fill.imageOffsetY',
  'Background.Fill.imageBlend',
  'Background.Fill.imageBlur',
  'Background.Fill.imageTint',
  'Background.Fill.imageFlipH',
  'Background.Fill.imageFlipV',
  'Background.Fill.imageRotation',
  'Background.Fill.imageGrayscale',
  'Background.Fill.imageSaturation',
  'Background.Fill.imageBrightness',
  'Background.Fill.imageContrast',
  'Background.Fill.imageTileScale',
  'Background.Fill.imageClipMode',
];

const COMPONENT_BACKGROUND_OVERLAY_PATHS = [
  'Background.Fill.overlayEnabled',
  'Background.Fill.overlayMuted',
  'Background.Fill.overlaySrc',
  'Background.Fill.overlayOpacity',
  'Background.Fill.overlayFit',
  'Background.Fill.overlayAlign',
  'Background.Fill.overlayOffsetX',
  'Background.Fill.overlayOffsetY',
  'Background.Fill.overlayBlend',
  'Background.Fill.overlayBlur',
  'Background.Fill.overlayTint',
  'Background.Fill.overlayFlipH',
  'Background.Fill.overlayFlipV',
  'Background.Fill.overlayRotation',
  'Background.Fill.overlayGrayscale',
  'Background.Fill.overlaySaturation',
  'Background.Fill.overlayBrightness',
  'Background.Fill.overlayContrast',
  'Background.Fill.overlayTileScale',
  'Background.Fill.overlayClipMode',
];

const TEXT_FONT_PATHS = [
  'Text.Font.family',
  'Text.Font.weight',
  'Text.Font.weightValue',
  'Text.Font.style',
  'Text.Font.size',
  'Text.Font.wordSpacing',
  'Text.Font.letterSpacing',
];

const TEXT_TYPOGRAPHY_PATHS = [
  'Text.Font.caseMode',
  'Text.Font.scriptMode',
  'Text.Font.baselineShift',
  'Text.Font.ligatures',
  'Text.Font.stylisticAlternates',
  'Text.Font.oldstyleFigures',
  'Text.Font.tabularFigures',
  'Text.Font.fractions',
  'Text.Font.slashedZero',
  'Text.Font.variationAxes',
];

const TEXT_POSITION_PATHS = [
  'Text.Position.justification',
  'Text.Position.paddingLeft',
  'Text.Position.paddingRight',
  'Text.Position.paddingTop',
  'Text.Position.paddingBottom',
  'Text.Position.offsetX',
  'Text.Position.offsetY',
];

const TEXT_FLOW_PATHS = [
  'Text.Position.readingOrientation',
  'Text.Position.flowMode',
  'Text.Position.flowAngle',
  'Text.Position.flowStepX',
  'Text.Position.flowStepY',
  'Text.Position.flowRadius',
  'Text.Position.flowSweep',
  'Text.Position.flowDistribution',
  'Text.Position.flowFacing',
  'Text.Position.flowSide',
  'Text.Position.flowReverse',
  'Text.Position.flowStartOffset',
  'Text.Position.flowFixedAdvance',
  'Text.Position.flowAmplitude',
  'Text.Position.flowFrequency',
  'Text.Position.flowTurns',
  'Text.Position.flowPerimeterInset',
  'Text.Position.flowStairUnit',
  'Text.Position.flowPathStartX',
  'Text.Position.flowPathStartY',
  'Text.Position.flowPathC1X',
  'Text.Position.flowPathC1Y',
  'Text.Position.flowPathC2X',
  'Text.Position.flowPathC2Y',
  'Text.Position.flowPathEndX',
  'Text.Position.flowPathEndY',
  'Text.Position.flowPolylinePoints',
  'Text.Position.flowFreehandPoints',
  'Text.Position.orientation',
];

const TEXT_LINE_PATHS = [
  'Text.Font.underline',
  'Text.Font.underlineOffset',
  'Text.Font.underlineThickness',
  'Text.Font.underlineColour',
  'Text.Font.underlineInsetLeft',
  'Text.Font.underlineInsetRight',
  'Text.Font.underlineGap',
  'Text.Font.underlineLayer',
  'Text.Font.strikethrough',
  'Text.Font.strikethroughOffset',
  'Text.Font.strikethroughThickness',
  'Text.Font.strikethroughColour',
  'Text.Font.strikethroughInsetLeft',
  'Text.Font.strikethroughInsetRight',
  'Text.Font.strikethroughGap',
  'Text.Font.strikethroughLayer',
  'Text.Font.overline',
  'Text.Font.overlineOffset',
  'Text.Font.overlineThickness',
  'Text.Font.overlineColour',
  'Text.Font.overlineInsetLeft',
  'Text.Font.overlineInsetRight',
  'Text.Font.overlineGap',
  'Text.Font.overlineLayer',
];

export const PRESET_SCOPE_OPTIONS = {
  'component:background': [
    { id: 'order', label: 'Order', paths: COMPONENT_BACKGROUND_ORDER_PATHS },
    { id: 'solid', label: 'Solid', paths: COMPONENT_BACKGROUND_SOLID_PATHS },
    { id: 'gradient', label: 'Gradient', paths: COMPONENT_BACKGROUND_GRADIENT_PATHS },
    { id: 'image', label: 'Image', paths: COMPONENT_BACKGROUND_IMAGE_PATHS },
    { id: 'overlay', label: 'Overlay', paths: COMPONENT_BACKGROUND_OVERLAY_PATHS },
  ],
  'component:border': [
    { id: 'border', label: 'Border', paths: ['Background.Border'] },
    { id: 'corners', label: 'Corners', paths: ['Background.Corners'] },
  ],
  'component:text': [
    { id: 'text', label: 'Text', paths: ['Text.content'] },
    { id: 'font', label: 'Font', paths: TEXT_FONT_PATHS },
    { id: 'typography', label: 'Typography', paths: TEXT_TYPOGRAPHY_PATHS },
    { id: 'multiline', label: 'Multiline', paths: ['Text.Multiline'] },
    { id: 'position', label: 'Position', paths: TEXT_POSITION_PATHS },
    { id: 'fill', label: 'Fill', paths: ['Text.Fill'] },
    { id: 'flow', label: 'Flow', paths: TEXT_FLOW_PATHS },
    { id: 'effects', label: 'Effects', paths: ['Text.Effects'] },
    { id: 'line', label: 'Line', paths: TEXT_LINE_PATHS },
  ],
  'component:icon': [
    { id: 'icon', label: 'Icon', paths: ['Icon.source', 'Icon.assetId', 'Icon.name', 'Icon.size', 'Icon.fit'] },
  ],
  'component:effects': [
    { id: 'shadows', label: 'Shadows', paths: ['Effects.Shadows'] },
    { id: 'bevel', label: 'Bevel', paths: ['Effects.Bevel'] },
    { id: 'filters', label: 'Filters', paths: ['Effects.Filters'] },
    { id: 'blend', label: 'Blend', paths: ['Effects.Blend'] },
  ],
  'panel:background': [
    { id: 'order', label: 'Order', paths: ['bgLayerOrder'] },
    { id: 'solid', label: 'Solid', paths: ['bgSolid', 'bgColour'] },
    { id: 'gradient', label: 'Gradient', paths: ['bgGradientEnabled', 'bgGradientOpacity', 'bgGradientName', 'bgGradient'] },
    {
      id: 'image',
      label: 'Image',
      paths: [
        'bgImageEnabled',
        'bgImage',
        'bgImageOpacity',
        'bgImageFit',
        'bgImageAlign',
        'bgImageOffsetX',
        'bgImageOffsetY',
        'bgImageBlend',
        'bgImageBlur',
        'bgImageTint',
        'bgImageFlipH',
        'bgImageFlipV',
        'bgImageRotation',
        'bgImageGrayscale',
        'bgImageSaturation',
        'bgImageBrightness',
        'bgImageContrast',
        'bgImageTileScale',
      ],
    },
    {
      id: 'texture',
      label: 'Texture',
      paths: [
        'bgTextureEnabled',
        'bgTexture',
        'bgTextureOpacity',
        'bgTextureFit',
        'bgTextureAlign',
        'bgTextureOffsetX',
        'bgTextureOffsetY',
        'bgTextureBlend',
        'bgTextureBlur',
        'bgTextureTint',
        'bgTextureFlipH',
        'bgTextureFlipV',
        'bgTextureRotation',
        'bgTextureGrayscale',
        'bgTextureSaturation',
        'bgTextureBrightness',
        'bgTextureContrast',
        'bgTextureTileScale',
      ],
    },
  ],
  'panel:grid': [
    { id: 'grid', label: 'Grid', paths: ['gridEnabled', 'snapToGrid', 'gridSize', 'gridLineWidth', 'gridType', 'gridColour'] },
    { id: 'subdivision', label: 'Subdivision', paths: ['gridSubdivision', 'gridSubColour'] },
    { id: 'origin', label: 'Origin', paths: ['gridCentered', 'gridOriginX', 'gridOriginY'] },
  ],
};

export function getPresetScopeOptions(domain) {
  return PRESET_SCOPE_OPTIONS[domain] ?? [];
}
