// genCpp.mjs — generate a buildable C++ handler module from a panel's C++ scripts.
//
// Output: <outDir>/{glue.cpp, CMakeLists.txt}. Each script's source is wrapped in its own namespace
// (so two controls can both define onValueChanged), and a dispatch table routes (scriptId, event) to
// the right namespace's function. The module is built with `add_library(MODULE)` to ce_handlers_cpp.
// <ext>, the exact name the host's NativeHandlerEngine looks for. Build-unverified until run on a real
// toolchain (see native-handlers-design.md).
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

// A stable C++ identifier fragment from a script id.
function sanitize(id) {
  return String(id).replace(/[^A-Za-z0-9_]/g, '_');
}
// C string literal escaping for the dispatch table.
function cstr(s) {
  return JSON.stringify(String(s)); // JSON string escaping is valid C string escaping for our ids/events
}

export function generateCppModule({ scripts, outDir, abiHeaderDir, runtimeHeaderDir }) {
  mkdirSync(outDir, { recursive: true });
  const usable = (scripts ?? []).filter((s) => s?.enabled !== false && typeof s?.source === 'string' && s.source.trim() && s.event);

  const namespaces = usable.map((s) => `namespace ce_s_${sanitize(s.id)} {\n${s.source}\n} // ${s.name ?? s.id}`).join('\n\n');
  const entries = usable
    .map((s) => `    { ${cstr(s.id)}, ${cstr(s.event)}, &ce_s_${sanitize(s.id)}::${s.event} },`)
    .join('\n');

  const glue = `// GENERATED by genCpp.mjs — do not edit. Per-panel C++ handler module.
#include "ce_runtime.h"
using namespace ce;

${namespaces}

namespace {
struct Entry { const char* sid; const char* ev; void (*fn)(CeContext&, const CeEvent&); };
const Entry kEntries[] = {
${entries}
};
const CeHostVtable* g_host = nullptr;

inline bool eq(const CeStr& a, const char* b) {
  const size_t bl = std::strlen(b);
  return (size_t) a.len == bl && std::memcmp(a.ptr, b, bl) == 0;
}
} // namespace

extern "C" {

CE_EXPORT uint32_t CE_CALL ce_handler_abi_version(void) { return CE_ABI_VERSION; }

CE_EXPORT int CE_CALL ce_handler_init(const CeHostVtable* host, void** out_state) {
  if (host == nullptr || host->abi_version != CE_ABI_VERSION) return -1;
  g_host = host;
  *out_state = (void*) host;   // stateless module; the host vtable is all we need
  return 0;
}

CE_EXPORT int CE_CALL ce_handler_has(void* /*state*/, CeStr sid, CeStr ev) {
  for (const auto& e : kEntries) if (eq(sid, e.sid) && eq(ev, e.ev)) return 1;
  return 0;
}

CE_EXPORT int CE_CALL ce_handler_dispatch(void* /*state*/, CeStr sid, CeStr ev,
                                          const CeValue* payload, CeValue* /*out_result*/) {
  for (const auto& e : kEntries) {
    if (eq(sid, e.sid) && eq(ev, e.ev)) {
      CeContext ctx(g_host);
      CeEvent evt(payload);
      e.fn(ctx, evt);        // value-returning handlers (onDawSaveState) are a TODO — see design §4
      return 0;
    }
  }
  return 0; // no such handler is not an error
}

CE_EXPORT void CE_CALL ce_handler_shutdown(void* /*state*/) { g_host = nullptr; }

} // extern "C"
`;

  const cmake = `cmake_minimum_required(VERSION 3.20)
project(ce_handlers_cpp LANGUAGES CXX)
add_library(ce_handlers_cpp MODULE glue.cpp)
target_compile_features(ce_handlers_cpp PRIVATE cxx_std_20)
target_include_directories(ce_handlers_cpp PRIVATE "${abiHeaderDir.replace(/\\/g, '/')}" "${runtimeHeaderDir.replace(/\\/g, '/')}")
set_target_properties(ce_handlers_cpp PROPERTIES
  PREFIX "" CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON POSITION_INDEPENDENT_CODE ON)
if (APPLE)
  set_target_properties(ce_handlers_cpp PROPERTIES SUFFIX ".dylib")
endif()
# Harden (does NOT sandbox — see design §5): catch some corruption earlier and louder.
if (MSVC)
  target_compile_options(ce_handlers_cpp PRIVATE /GS /guard:cf /EHsc)
else()
  target_compile_options(ce_handlers_cpp PRIVATE -fstack-protector-strong)
endif()
`;

  writeFileSync(path.join(outDir, 'glue.cpp'), glue);
  writeFileSync(path.join(outDir, 'CMakeLists.txt'), cmake);
  return { dir: outDir, moduleName: 'ce_handlers_cpp', handlerCount: usable.length };
}
